function i(a){throw a;}var l=void 0,m=!0,p=null,q=!1;function aa(){return function(){}}var r,s={},ba=q,ca;function u(a,b){ca.innerHTML+=(b?'<p class="'+b+'">':"<p>")+a+"</p>"}function da(a,b,c){ba!==m&&(ba=m,b=b.split("/"),b=b[b.length-1],a=a+"  "+b+":"+c,u('<p class="error">'+a+"</p>"),c=new XMLHttpRequest,c.open("POST","post.php"),c.setRequestHeader("Content-type","application/x-www-form-urlencoded"),c.send("data=err&msg="+a),ba=q)}
window.onload=function(){ca=document.getElementById("output");window.onerror=da;u("<h2>WebGL Driver (alpha)</h2>");u("<p>Made by Ugnius Kavaliauskas and Rimvydas Klementavi&#269;ius</p>");u("<p>Testing browser...</p>");u("<p>"+navigator.userAgent+"</p>");var a=q,b;b=document.createElement("canvas");b.getContext("experimental-webgl")||b.getContext("webgl")?u("WebGL is supported","success"):(u("WebGL is not supported!","error"),a=m);window.MozWebSocket||window.WebSocket?u("WebSockets are supported",
"success"):(u("WebSockets are not supported!","error"),a=m);navigator.pointer||navigator.webkitPointer?u("Mouse Lock API is supported","success"):u("Mouse Lock API is not supported!","warning");navigator.gamepads||navigator.webkitGamepads?u("Gamepad API is supported","success"):u("Gamepad API is not supported!","warning");window.AudioContext||window.webkitAudioContext?u("Web Audio API is supported","success"):u("Web Audio API is not supported!","warning");a?u("Sorry, this game will not work here =/"):
(u("Loading application..."),x.hg())};window.D=window.D||{};window.AudioContext=window.AudioContext||window.webkitAudioContext;function ea(){if(this.Y=window.AudioContext?new AudioContext:p)this.q={},this.Zb=this.Y.createGainNode(),this.Zb.connect(this.Y.destination)}function ia(a,b){a.Y&&(a.Zb.gain.value=s.sa(b,0,1))}function ja(a){return a.Y?a.Zb.gain.value:0}
function ka(a,b,c){if(a.Y){var d,e;"string"!==typeof b&&i(Error("Wrong audio url name!"));a.q[b]!==l?"function"===typeof c&&c():(a.q[b]=e={ready:q,buffer:p},d=new XMLHttpRequest,d.open("GET","sound/"+b,m),d.responseType="arraybuffer",d.onload=function(){a.Y.decodeAudioData(d.response,function(a){e.buffer=a;e.W=m;"function"===typeof c&&c()})},d.send())}else"function"===typeof c&&c()}
ea.prototype.play=function(a,b){if(this.Y){var c,d=this;this.q[a]===l&&(ka(this,a,function(){d.play(a,b)}),u('Audio resource was not preloaded "'+a+'"',"warn"));this.q[a].buffer===p?u("Audio buffer is not ready","warn"):(c=this.Y.createBufferSource(),c.buffer=this.q[a].buffer,c.connect(b!==l?b:this.Zb),c.noteOn(0))}};
function la(a,b,c){if(!a.Y)return p;var d=a.Y.createBufferSource();a.Y?((a.q[b]===l||a.q[b].buffer===p)&&i(Error("Audio resource is not ready!")),a=a.q[b].buffer):a=p;d.buffer=a;d.gain.value=0;d.loop=m;c!==l&&d.connect(c);return d};function ma(){this.$c=[];this.fe=q;this.Ya=[];this.de=[];this.xc=[];this.ee=[];this.vc=[];this.ae=[];this.be=[];this.ad=[];this.wc=[];this.Tb=this.he=this.ge=this.zc=this.yc=this.fd=this.ed=this.hd=this.gd=0;this.gb=this.T=p;na(this);this.Jc=navigator.pointer||navigator.webkitPointer?m:q;this.we=navigator.gamepads||navigator.webkitGamepads?m:q}
function na(a){navigator.pointer=navigator.pointer||navigator.webkitPointer;window.oncontextmenu=function(){return q};window.onkeydown=function(b){a.Ya[b.keyCode]||(a.xc[b.keyCode]=m);a.Ya[b.keyCode]=m;a.ad.push(b.keyCode);return b.keyCode===a.Md&&a.fe?(oa(a),q):a.$c[b.keyCode]?m:q};window.onkeyup=function(b){a.Ya[b.keyCode]=q;a.ee[b.keyCode]=m};window.onblur=function(){for(var b in a.Ya)a.Ya.hasOwnProperty(b)&&(a.Ya[b]&&(a.xc[b]=m),a.Ya[b]=q);a.Qf=q};window.onfocus=function(){a.Qf=m};window.onmousedown=
function(b){a.vc[b.button]||(a.ae[b.button]=m);a.vc[b.button]=m;return q};window.onmouseup=function(b){a.vc[b.button]=q;a.be[b.button]=m};window.ondblclick=function(){return q};window.onmousemove=function(b){a.Jc&&(a.yc+=b.webkitMovementX,a.zc+=b.webkitMovementY);a.gd=b.clientX;a.hd=b.clientY};window.addEventListener("mousewheel",function(b){a.Tb+=b.wheelDelta/Math.abs(b.wheelDelta)},q);window.addEventListener("DOMMouseScroll",function(b){a.Tb-=b.detail/Math.abs(b.detail)},q)}
function oa(a){var b=document.body;b.webkitRequestFullScreen(b.ALLOW_KEYBOARD_INPUT);a.Jc&&navigator.pointer.lock(b,aa(),function(){i(Error("Failed to enable pointer lock"))})}function pa(){var a=x.input,b=[x.input.nf,x.input.Md,x.input.mf,x.input.Ld],c;a.$c=[];for(c=0;c<b.length;c++)a.$c[b[c]]=m}function qa(a,b){var c;for(c=0;c<a.wc.length;c++){var d=ra(a,a.wc[c]);""!==d&&(b+=d);a.wc[c]===a.Yc&&(b=b.slice(0,b.length-1))}return b}
function ra(a,b){switch(b){case a.Gd:return"a";case a.jf:return"b";case a.Hd:return"c";case a.Id:return"d";case a.kf:return"e";case a.Ld:return"f";case a.of:return"g";case a.pf:return"h";case a.qf:return"i";case a.rf:return"j";case a.sf:return"k";case a.Nd:return"l";case a.tf:return"m";case a.uf:return"n";case a.Od:return"o";case a.vf:return"p";case a.Pd:return"q";case a.Qd:return"r";case a.Rd:return"s";case a.xf:return"t";case a.zf:return"u";case a.Af:return"v";case a.Td:return"w";case a.Bf:return"x";
case a.Cf:return"y";case a.Ud:return"z";case a.Ed:return"1";case a.Fd:return"2";case a.bf:return"3";case a.cf:return"4";case a.df:return"5";case a.ef:return"6";case a.ff:return"7";case a.gf:return"8";case a.hf:return"9";case a.af:return"0"}return""}function y(a,b){return a.de[b]===m?m:q}function z(a,b){return a.Ya[b]===m?m:q}function sa(a,b){return a.T&&a.T.axes&&a.T.axes[b]!==l?a.T.axes[b]:0}function ta(a,b){return a.T&&a.T.buttons&&a.T.buttons[b]!==l?a.T.buttons[b]:0}
function A(a,b){var c=a.T,d=a.gb;return c&&c.buttons&&c.buttons[b]!==l&&d&&d.buttons&&d.buttons[b]!==l&&0.1>=d.buttons[b]&&0.1<c.buttons[b]?m:q}r=ma.prototype;r.lf=112;r.nf=116;r.Md=122;r.mf=123;r.af=48;r.Ed=49;r.Fd=50;r.bf=51;r.cf=52;r.df=53;r.ef=54;r.ff=55;r.gf=56;r.hf=57;r.Gd=65;r.jf=66;r.Hd=67;r.Id=68;r.kf=69;r.Ld=70;r.of=71;r.pf=72;r.qf=73;r.rf=74;r.sf=75;r.Nd=76;r.tf=77;r.uf=78;r.Od=79;r.vf=80;r.Pd=81;r.Qd=82;r.Rd=83;r.xf=84;r.zf=85;r.Af=86;r.Td=87;r.Bf=88;r.Cf=89;r.Ud=90;r.sc=37;r.tc=39;
r.Sd=38;r.Jd=40;r.Kd=13;r.Yc=8;r.wf=16;r.yf=9;r.Xe=2;r.Vd=0;r.Wd=1;r.Of=3;r.Jf=4;r.Lf=5;r.Kf=6;r.Mf=7;r.Hf=8;r.Nf=12;r.If=13;r.Xd=14;r.Yd=15;r.Df=0;r.Ef=1;r.Ff=2;r.Gf=3;var ua,va,wa,xa,ya;function za(a){ua=a;va=[];wa=0;xa=p;Aa();ya=0}function Aa(){try{xa=new WebSocket(ua)}catch(a){}try{xa=new MozWebSocket(ua)}catch(b){}xa===p?console.log("WARNING: NetworkInterface::connect - WebSocket is not supported"):(xa.binaryType="arraybuffer",xa.onopen=Ba,xa.onclose=Ca,xa.onmessage=Fa,ya=1)}function Ba(){console.log("INFO: NetworkInterface - succesfuly connected to "+ua);ya=2}
function Ca(){0===wa?(wa=1,ua="ws://localhost:8001",Aa()):(console.log("WARNING: NetworkInterface::onclose - failed to connect to WebSockets server!"),ya=3)}function Fa(a){va.push(a.data)}function Ga(a){xa!==p&&1===xa.readyState&&xa.send(a)};var x={};window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame;
x.hg=function(){x.loaded=0;x.vd=0;x.eg=0.002;x.frame=0;x.u=0;x.time=(new Date).getTime();x.hb=0;x.freeze=q;x.Cg=0;x.Za=1;x.Ig=m;x.nb=m;x.Tg=m;x.Ib=q;x.focus=0.15;x.Gg=q;x.me=1;x.Db=0.5;x.Ka=1;x.Fa=10;x.ka=p;x.Aa=0;x.Zc=1;x.Zd=2;x.zb=3;x.uc=4;x.z=x.Aa;x.We="ws://"+(window.location.hostname||"localhost")+":8001";x.Cc=0;x.Ie=0;x.He=0;x.Ge=0;x.id=-1;x.H=[];x.$a=[];x.La=[];x.jb=[];x.Oc=[];window.onbeforeunload=x.Vc;x.gg();x.input=new ma;pa();x.input.fe=q;x.canvas=document.getElementById("canvas");x.ca=
new Ha(x.canvas,{antialias:q});x.ca!==p&&(window.addEventListener("resize",x.Ec,q),x.Ec(),x.g=new ea,ia(x.g,x.Db),Ia(x.ca,"depth",m),Ia(x.ca,"scene"),Ia(x.ca,"left"),Ia(x.ca,"right"),za(x.We),x.ye=document.getElementById("help"),x.debug=document.getElementById("debug"),x.$f=document.getElementById("debug2"),x.$f.style.display="none",x.ka=new Ja(x),x.ka.load(function(){x.nb||(x.ye.style.display="none");ca.style.display="none";window.requestAnimationFrame(x.Oe,x.canvas)}))};
x.Ec=function(){var a=x.ca,b=window.innerWidth*x.Ka,c=window.innerHeight*x.Ka;a.canvas.width=b;a.width=b;a.canvas.height=c;a.height=c;a.pd=m;a.d.viewport(0,0,b,c);x.Za=window.innerWidth/window.innerHeight;x.ka&&"function"===typeof x.ka.Le&&x.ka.Le(window.innerWidth,window.innerHeight)};x.Vc=function(){x.ca.Vc();x.jg()};
x.jg=function(){"undefined"!==typeof localStorage&&localStorage.setItem("settings",window.JSON.stringify({fieldOfView:x.Ib,camMode:x.me,audioGain:x.Db,canvasScale:x.Ka,renderDis:x.Fa,help:x.nb}))};
x.gg=function(){if("undefined"!==typeof localStorage){var a=""+localStorage.getItem("settings");if(a&&(a=window.JSON.parse(a)))if(a.fieldOfView!==l&&(x.Ib=a.fieldOfView),a.camMode!==l&&(x.me=a.camMode),a.audioGain!==l&&(x.Db=a.audioGain),a.canvasScale!==l&&(x.Ka=a.canvasScale),a.renderDis!==l&&(x.Fa=a.renderDis),a.help!==l)x.nb=a.help}};
x.Oe=function(a){var a=(new Date).getTime(),b=x.input;b.de=b.xc;b.xc={};b.ee={};b.ae={};b.be={};!b.Jc||!navigator.pointer.isLocked?(b.ed=b.gd-b.ge,b.fd=b.hd-b.he,b.ge=b.gd,b.he=b.hd):(b.ed=b.yc,b.fd=b.zc,b.yc=0,b.zc=0);b.Tb=0;b.wc=b.ad;b.ad=[];b=x.input;if(b.we){var c=(navigator.gamepads||navigator.webkitGamepads)[0],d=0;if(c!==l){b.gb===p&&(b.gb={},b.gb.buttons=[],b.gb.axes=[]);b.T===p&&(b.T={},b.T.buttons=[],b.T.axes=[]);if(b.T){for(d=0;16>d;d++)b.gb.buttons[d]=b.T.buttons[d];for(d=0;4>d;d++)b.gb.axes[d]=
b.T.axes[d]}for(d=0;16>d;d++)b.T.buttons[d]=c.buttons[d];for(d=0;4>d;d++)b.T.axes[d]=c.axes[d]}}x.ka&&("function"===typeof x.ka.update&&x.ka.update(x.input,a),"function"===typeof x.ka.qb&&x.ka.qb(x.ca));x.debug.innerHTML=x.ka.debug?"Triangles: "+x.Cc+"<br/>Server state: "+x.z+"<br/>ping average: "+x.ka.pb+"<br/>Network interface: "+ya+"<br/>":"";x.Cc=0;y(x.input,x.input.lf)&&(x.nb=!x.nb,console.log(x.nb),x.ye.style.display=x.nb?"inline":"none");x.vd=0;x.frame++;window.requestAnimationFrame(x.Oe,x.canvas)};
x.Vf=function(a,b){z(b,b.Sd)?(a.C+=0.22,1<a.C&&(a.C=1)):a.C=0.1>=a.C?0:a.C-0.1;z(b,b.Jd)?(a.v+=0.2,1<a.v&&(a.v=1)):a.v=0.2>a.v?0:a.v-0.2;z(b,b.sc)&&(a.t+=0.1);z(b,b.tc)&&(a.t-=0.1);!z(b,b.sc)&&!z(b,b.tc)&&(a.t=0.1>=Math.abs(a.t)?0:0<a.t?a.t-0.1:a.t+0.1);1<a.t&&(a.t=1);-1>a.t&&(a.t=-1);y(b,b.Fd)&&(a.M++,6<a.M&&(a.M=6));y(b,b.Ed)&&(a.M--,-1>a.M&&(a.M=-1));if(b.we&&(0.02<ta(b,6)&&(a.v=ta(b,6)),0.02<ta(b,7)&&(a.C=ta(b,7)),0.05<Math.abs(sa(b,0))))a.t=-sa(b,0)};
x.Ze=function(a,b,c,d){var e,f,g,h,c=(c||1/60)*(d||100),d=a.rotation[0];e=a.rotation[1];f=a.position[0];g=a.position[1];h=a.position[2];z(b,b.Gd)&&(f-=Math.cos(-e)*c,h-=Math.sin(-e)*c);z(b,b.Id)&&(f+=Math.cos(-e)*c,h+=Math.sin(-e)*c);z(b,b.Rd)&&(f-=Math.sin(-e)*c,h+=Math.cos(-e)*c);z(b,b.Td)&&(f+=Math.sin(-e)*c,h-=Math.cos(-e)*c);z(b,b.Pd)&&(g+=c);z(b,b.Ud)&&(g-=c);if(b.Jc&&navigator.pointer.isLocked||b.vc[b.Xe])e-=0.005*b.ed,d-=0.005*b.fd;a.setPosition(f,g,h);Ka(a,d,e)};
x.$e=function(a,b,c){var d,e,f,g,h,c=400*(c||1/60);d=a.rotation[0];e=a.rotation[1];f=a.position[0];g=a.position[1];h=a.position[2];var j=sa(b,b.Ff),k=sa(b,b.Gf),o=sa(b,b.Df),n=sa(b,b.Ef),o=0.5*s.sa(Math.abs(o)-0.05,0,1)*s.rb(o)*c,n=0.5*s.sa(Math.abs(n)-0.05,0,1)*s.rb(n)*c;f-=Math.sin(-e)*n-Math.cos(-e)*o;h+=Math.cos(-e)*n+Math.sin(-e)*o;g+=4*(ta(b,b.Mf)-ta(b,b.Kf));e-=0.01*s.sa(Math.abs(j)-0.1,0,1)*s.rb(j)*c;d-=0.01*s.sa(Math.abs(k)-0.1,0,1)*s.rb(k)*c;1.5<d&&(d=1.5);-1.5>d&&(d=-1.5);a.setPosition(f,
g,h);Ka(a,d,e)};"undefined"!==typeof exports?global.D=global.D||{}:window.D=window.D||{};
function Ha(a,b){if(!a||"function"!==typeof a.getContext)this.d=p;else{this.d=a.getContext("experimental-webgl",b)||a.getContext("webgl",b);this.canvas=a;this.W=q;this.ib=p;this.R={};this.wb={};this.dc={};this.Oa={};this.d.clearColor(1,1,1,1);this.d.enable(this.d.DEPTH_TEST);this.d.blendFunc(this.d.SRC_ALPHA,this.d.ONE_MINUS_SRC_ALPHA);this.d.enable(this.d.CULL_FACE);this.width=this.canvas.width;this.height=this.canvas.height;this.pd=q;this.Na=m;this.Ja=q;this.ze=p;this.activeTexture=0;this.le=[];
var c=new Float32Array([-1,1,0,-1,-1,0,1,-1,0,1,-1,0,1,1,0,-1,1,0]);this.Wb=this.d.createBuffer();this.d.bindBuffer(this.d.ARRAY_BUFFER,this.Wb);this.d.bufferData(this.d.ARRAY_BUFFER,c,this.d.STATIC_DRAW);this.d.getExtension("OES_texture_float")}}Ha.prototype.Vc=function(){var a=this.d,b,c;for(b in this.Oa)this.Oa.hasOwnProperty(b)&&(c=this.Oa[b],a.deleteFramebuffer(c.Hb),a.deleteTexture(c.ia),a.deleteRenderbuffer(c.Nc));for(b in this.wb)this.wb.hasOwnProperty(b)&&a.deleteTexture(this.wb[b].ia)};
Ha.prototype.qb=function(a,b){var c=this.d,d;a.md&&c.clear(c.COLOR_BUFFER_BIT|c.DEPTH_BUFFER_BIT);for(d=0;d<a.da.length;d++)c=a.da[d],La(this,a,b,c,d);for(d=0;d<a.lb.length;d++)c=a.lb[d],La(this,a,b,c,d)};
function La(a,b,c,d,e){var f=a.d,g,h,j;if(d.ua&&(d.m.W&&d.na.W)&&(x.ka.Me%16===e%16&&(d.mb=d.K&&s.Da.kg(c.position,d.o)>0.1*d.K*x.Fa),!d.mb)){a.ib!==d.na&&(f.useProgram(d.na.ea),a.ib=d.na,f.uniformMatrix4fv(d.na.Ca,q,c.Fc()));c.$===m&&f.uniformMatrix4fv(d.na.Ca,q,c.Fc());f.uniformMatrix4fv(d.na.w,q,Ma(d));d.na.ba&&f.uniformMatrix3fv(d.na.ba,q,d.ba);for(j=0;j<d.na.Cd;j++)switch(e=d.na.pa[j],g=d.na.ja[j],h=d.e[e]||d.m.e[e]||b.e[e]||c.e[e],h===l&&i(Error('Object has undefined uniform: "'+s.I[e]+'", "'+
d.m.X+'"')),s.P[e]){case 10:f.uniform3fv(g,h);break;case 11:f.uniform4fv(g,h);break;case 0:f.uniform1f(g,h);break;case 4:f.uniform1i(g,h);break;default:i(Error("Bad unifrom type: "+s.I[e]+", "+s.P[e]))}d.Na===q?a.Na===m&&(a.Na=q,f.disable(f.CULL_FACE)):a.Na===q&&(a.Na=m,f.enable(f.CULL_FACE));d.Ja===q?a.Ja===m&&(a.Ja=q,f.disable(f.BLEND)):a.Ja===q&&(a.Ja=m,f.enable(f.BLEND));d.m.V&&d.text===l&&(x.Cc+=d.m.V);d.m.Ac(f,d.na,d)}}
function Na(a,b,c){var d=a.d,e=B(a,"depth");if(e.W){d.useProgram(e.ea);a.ib=e;d.uniformMatrix4fv(e.Ca,q,c.Fc());for(a=0;a<b.da.length;a++)if(c=b.da[a],c.ua&&c.m.W&&c.m.Bb){if(c.mb)return;d.uniformMatrix4fv(e.w,q,Ma(c));x.vd++;c.m.Bb(d,e,c)}for(a=0;a<b.lb.length;a++)if(c=b.lb[a],c.ua&&c.m.W&&c.m.Bb){if(c.mb)break;d.uniformMatrix4fv(e.w,q,Ma(c));x.vd++;c.m.Bb(d,e,c)}}}
function Oa(a,b,c,d){this.d=a;this.Hb=a.createFramebuffer();this.ia=a.createTexture();this.Nc=a.createRenderbuffer();this.width=b;this.height=c;this.type=d===m?a.FLOAT:a.UNSIGNED_BYTE;a.bindFramebuffer(a.FRAMEBUFFER,this.Hb);a.bindTexture(a.TEXTURE_2D,this.ia);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);
a.texImage2D(a.TEXTURE_2D,0,a.RGBA,this.width,this.height,0,a.RGBA,this.type,p);a.bindRenderbuffer(a.RENDERBUFFER,this.Nc);a.renderbufferStorage(a.RENDERBUFFER,a.DEPTH_COMPONENT16,this.width,this.height);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,this.ia,0);a.framebufferRenderbuffer(a.FRAMEBUFFER,a.DEPTH_ATTACHMENT,a.RENDERBUFFER,this.Nc);a.bindTexture(a.TEXTURE_2D,p);a.bindRenderbuffer(a.RENDERBUFFER,p);a.bindFramebuffer(a.FRAMEBUFFER,p)}
function Ia(a,b,c){var d=a.width,e=a.height;a.Oa[b]||(a.Oa[b]=new Oa(a.d,d,e,c));return a.Oa[b]}
function Pa(a,b,c){"string"!==typeof b&&i("Wrong shader name!");if("undefined"!==typeof a.R[b])c&&c();else switch(b){case "color":a.R[b]=new E(a,"color.vsh","color.fsh",["aVerPosition"],[s.b.p],c);break;case "normal":a.R[b]=new E(a,"normal.vsh","normal.fsh",["aVerPosition","aVerNormal"],[s.b.Sc,s.b.Tc,s.b.yb,s.b.p],c);break;case "car":a.R[b]=new E(a,"car.vsh","car.fsh",["aVerPosition","aVerNormal","aTexCoord"],"uLightDirection uColor uTex0 uTex1 uTex2 uCamPosition".split(" "),c);break;case "add":a.R[b]=
new E(a,"add.vsh","add.fsh",["aVerPosition","aVerNormal","aTexCoord"],"uLightDirection uFog uColor uTex0 uTex1 uTex2 uCamPosition".split(" "),c);break;case "terrain":a.R[b]=new E(a,"terrain.vsh","terrain.fsh",["aVerPosition","aVerNormal","aTexCoord"],[s.b.yb,s.b.oc,s.b.qc,s.b.Rb],c);break;case "transparent":a.R[b]=new E(a,"transparent.vsh","transparent.fsh",["aVerPosition","aVerNormal","aTexCoord"],[s.b.yb,s.b.oc,s.b.qc,s.b.Rb],c);break;case "water":a.R[b]=new E(a,"water.vsh","water.fsh",["aVerPosition",
"aVerNormal","aTexCoord"],["uCamPosition","uLightDirection","uFog","uTime","uTex0"],c);break;case "multicol":a.R[b]=new E(a,"multicol.vsh","multicol.fsh",["aVerPosition","aVerNormal","aTexCoord"],[s.b.yb,s.b.oc,s.b.Rb,s.b.Uc,s.b.Se,s.b.Te,s.b.Bd],c);break;case "multicolroad":a.R[b]=new E(a,"multicolroad.vsh","multicolroad.fsh",["aVerPosition","aVerNormal","aTexCoord"],"uLightDirection uFog uTex0 uTex1 uTex2 uTex3 uCamPosition".split(" "),c);break;case "sky":a.R[b]=new E(a,"sky.vsh","sky.fsh",["aVerPosition",
"aTexCoord"],["uTex0","uCamPosition","uTime"],c);break;case "text":a.R[b]=new E(a,"text.vsh","text.fsh",["aVerPosition","aVerNormal"],[s.b.Sc,s.b.Tc,s.b.yb,s.b.p,s.b.pc],c);break;case "vignette":a.R[b]=new E(a,"vignette.vsh","vignette.fsh",["aVerPosition"],[],c);break;case "fade":a.R[b]=new E(a,"fade.vsh","fade.fsh",["aVerPosition"],[s.b.Qe],c);break;case "depth":a.R[b]=new E(a,"depth.vsh","depth.fsh",["aVerPosition"],["uOffset"],c);break;case "rbuffer":a.R[b]=new E(a,"rbuffer.vsh","rbuffer.fsh",
["aVerPosition"],["uTex0"],c);break;case "3d":a.R[b]=new E(a,"3d.vsh","3d.fsh",["aVerPosition"],["uTex0","uTex1"],c);break;case "vgauss":a.R[b]=new E(a,"vgauss.vsh","vgauss.fsh",["aVerPosition"],["uTex0","uTex1","uBlur","uFocus"],c);break;case "hgauss":a.R[b]=new E(a,"hgauss.vsh","hgauss.fsh",["aVerPosition"],["uTex0","uTex1","uBlur","uFocus"],c);break;default:i("Unkonwn shader "+b)}}function B(a,b){"string"!==typeof b&&i("Wrong shader name!");"undefined"===typeof a.R[b]&&Pa(a,b);return a.R[b]}
function Qa(a,b,c,d,e){"string"!==typeof b&&i("Wrong texture url name!");"undefined"!==typeof a.wb[b]?c&&c():a.wb[b]=new Ra(a.d,"textures/"+b,c,d,e)}function G(a,b,c,d){"string"!==typeof b&&i("Wrong texture name!");"undefined"===typeof a.wb[b]&&Qa(a,b,p,c,d);return a.wb[b]}function Sa(a,b,c,d){"string"!==typeof b&&i('Wrong mesh url! "'+b+'"');"undefined"!==typeof a.dc[b]?"function"===typeof d&&d():a.dc[b]=new Ta(a.d,"obj/"+b,c,d)}
function I(a,b){"string"!==typeof b&&i('Wrong mesh url! "'+b+'"');"undefined"===typeof a.dc[b]&&Sa(a,b);return a.dc[b]}
function Ra(a,b,c,d,e){var f=this;this.d=a;this.url=b;this.fb=c||p;this.Ce=d===q?q:m;this.alpha=e===m?m:q;this.ia=a.createTexture();this.cc=new Image;this.cc.onload=function(){var a=f.d;a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,1);a.bindTexture(a.TEXTURE_2D,f.ia);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,f.Ce===m?a.LINEAR_MIPMAP_NEAREST:a.LINEAR);f.alpha===m?a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,f.cc):a.texImage2D(a.TEXTURE_2D,
0,a.RGB,a.RGB,a.UNSIGNED_BYTE,f.cc);f.Ce===m&&a.generateMipmap(a.TEXTURE_2D);f.W=m;f.fb!==p&&(f.fb(),f.fb=p)};this.cc.onerror=function(){i('Error while loading image "'+b+'"')};this.cc.src=this.url;this.W=q}
function E(a,b,c,d,e,f){this.ce=a;this.Ia=a.d;this.Bc=b;this.Rf=c;this.$d=d;this.kd=e;this.fb=f||p;this.W=q;this.attributes={};this.Ub=[];this.ea=this.Ia.createProgram();this.cd=this.ld=p;this.Cd=0;this.pa=[];this.ja=[];Ua(this,this.Ia.VERTEX_SHADER,"shaders/"+b);Ua(this,this.Ia.FRAGMENT_SHADER,"shaders/"+c)}
function Ua(a,b,c){var d;d=new XMLHttpRequest;d.open("GET",c);d.onreadystatechange=function(){if(4===d.readyState){var c=d.responseText,f=a.Ia,g=f.createShader(b);f.shaderSource(g,c);f.compileShader(g);f.getShaderParameter(g,f.COMPILE_STATUS)||i(Error('ERROR: CGLC:initShaders - failed to compile shader: "'+(b===f.VERTEX_SHADER?a.Bc:a.Rf)+'"\n'+f.getShaderInfoLog(g)+f.deleteShader(g)));b===f.VERTEX_SHADER&&(a.ld=g);b===f.FRAGMENT_SHADER&&(a.cd=g);if(!(a.ld===p||a.cd===p)){var c=a.Ia,h;c.attachShader(a.ea,
a.ld);c.attachShader(a.ea,a.cd);c.linkProgram(a.ea);if(c.getProgramParameter(a.ea,c.LINK_STATUS)){for(f=0;f<a.$d.length;f++)h=a.$d[f].toString(),g=a.attributes[h]=c.getAttribLocation(a.ea,h),-1!==g?(c.enableVertexAttribArray(a.attributes[h]),a.Ub[g]=m):console.error('ERROR: Could not get attribute location "'+h+'"');for(f=0;f<a.kd.length;f++)g=a.kd[f],"string"===typeof g&&(g=s.I.indexOf(g),-1===g&&i(Error('shader uniform definition by string "'+a.kd[f]+'" was not found! '+a.Bc))),g===l&&i(Error("shader uniform "+
(f+1)+" id is undefined! "+a.Bc)),h=s.I[g],a.pa.push(g),a.ja.push(c.getUniformLocation(a.ea,h)),a.ja[a.Cd]===p&&console.log('WARNING: shader program "'+a.Bc+'" has undefined variable "'+h+'" '+g),a.Cd++;a.Ca=c.getUniformLocation(a.ea,"uPMatrix");a.w=c.getUniformLocation(a.ea,"uMVMatrix");a.ba=c.getUniformLocation(a.ea,"uNMatrix");for(h in a.attributes)a.attributes[h]===p&&console.log('WARNING: shader program has undefined variable "'+h+'"');a.W=m;"function"===typeof a.fb&&(a.fb(),a.fb=p)}else console.error("ERROR: Could not initialise shaders!")}}};
d.send()}function Va(a,b){var c=a.attributes[b];c===l?console.warn("Bad shader attribute name!"):a.Ub[c]===q&&(a.Ia.enableVertexAttribArray(c),a.Ub[c]=m)}function Wa(a,b,c,d){var e=a.Ia,f=a.ce,a=a.attributes[b];a===l&&i(Error('Bad shader attribute name "'+b+'"'));f.ze!==c&&(e.bindBuffer(e.ARRAY_BUFFER,c),f.ze=c,e.vertexAttribPointer(a,d,e.FLOAT,q,0,0))}
E.prototype.bindTexture=function(a,b){var c=this.ce,d=this.Ia;c.le[a]!==b&&(c.activeTexture!==a&&(d.activeTexture(a+33984),c.activeTexture=a),d.bindTexture(d.TEXTURE_2D,b),c.le[a]=b)};function Xa(){this.da=[];this.lb=[];this.e=[];this.md=q}Xa.prototype.add=function(a,b){"function"===typeof a.ie?a.ie(this):b===m?this.lb.push(a):this.da.push(a)};s.Ye=aa();s.Ye.prototype.Fc=aa();
function Ya(a,b,c,d){this.ue=a;this.Za=b;this.De=c;this.mb=d;this.e=[];this.position=J.create();this.rotation=J.create();this.L=J.create();this.Ee=J.create();this.nc=J.create();this.Ca=K.create();this.$=m}Ya.prototype.dd=function(){var a=this.position,b=this.rotation;K.Je(this.ue,this.Za,this.De,this.mb,this.Ca);K.rotate(this.Ca,-b[0],[1,0,0]);K.rotate(this.Ca,-b[1],[0,1,0]);K.rotate(this.Ca,-b[2],[0,0,1]);J.scale(a,-1,this.Ee);K.translate(this.Ca,this.Ee);this.e[s.b.Bd]=[a[0],a[1],a[2]];this.$=q};
Ya.prototype.setPosition=function(a,b,c){var d=this.position;d[0]===a&&d[1]===b&&d[2]===c||(d[0]=a,d[1]=b,d[2]=c,this.$=m)};function Ka(a,b,c){var d=a.rotation;d[0]===b&&d[1]===c&&0===d[2]||(d[0]=b,d[1]=c,d[2]=0,a.$=m)}Ya.prototype.Ae=function(a,b,c){var a=a-this.position[0],b=b-this.position[1],c=c-this.position[2],d;d=Math.atan(a/c);0<c&&(d+=Math.PI);Ka(this,Math.atan(b/Math.sqrt(a*a+c*c)),d)};Ya.prototype.Fc=function(){this.$&&this.dd();return this.Ca};s.f=0;s.b={};s.I=[];s.P=[];s.b.Rg=++s.f;
s.I[s.f]="uPMatrix";s.P[s.f]=18;s.b.Pg=++s.f;s.I[s.f]="uMMatrix";s.P[s.f]=18;s.b.Qg=++s.f;s.I[s.f]="uNMatrix";s.P[s.f]=17;s.b.yb=++s.f;s.I[s.f]="uLightDirection";s.P[s.f]=10;s.b.Sc=++s.f;s.I[s.f]="uAmbientColor";s.P[s.f]=10;s.b.Tc=++s.f;s.I[s.f]="uDirColor";s.P[s.f]=10;s.b.oc=++s.f;s.I[s.f]="uFog";s.P[s.f]=0;s.b.qc=++s.f;s.I[s.f]="uScale";s.P[s.f]=0;s.b.Rb=++s.f;s.I[s.f]="uTex0";s.P[s.f]=4;s.b.Uc=++s.f;s.I[s.f]="uTex1";s.P[s.f]=4;s.b.Se=++s.f;s.I[s.f]="uTex2";s.P[s.f]=4;s.b.Te=++s.f;s.I[s.f]="uTex3";
s.P[s.f]=4;s.b.p=++s.f;s.I[s.f]="uColor";s.P[s.f]=10;s.b.pc=++s.f;s.I[s.f]="uOffset";s.P[s.f]=4;s.b.Qe=++s.f;s.I[s.f]="uFade";s.P[s.f]=0;s.b.Pe=++s.f;s.I[s.f]="uBlur";s.P[s.f]=0;s.b.Re=++s.f;s.I[s.f]="uFocus";s.P[s.f]=0;s.b.Ue=++s.f;s.I[s.f]="uTime";s.P[s.f]=0;s.b.Bd=++s.f;s.I[s.f]="uCamPosition";s.P[s.f]=10;"undefined"!==typeof exports?s=global.D=global.D||s:window.D=window.D||{};
function Ja(a){this.a=a;this.time=(new Date).getTime()+6E4;this.hb=this.startTime=0;this.ab=0.002;this.Me=this.u=0;this.Wa="test";this.Ua="blabla";this.Fe=0;this.debug=q;this.J=0;this.Gc=[0.507,-0.407,0.3];this.h=new Xa;this.h.md=m;this.h.e[s.b.Sc]=[0.5,0.5,0.5];this.h.e[s.b.Tc]=[0.5,0.5,0.5];this.h.e[s.b.yb]=this.Gc;this.h.e[s.b.oc]=[2E3];this.h.e[s.b.qc]=[1];this.h.e[s.b.Ue]=[this.time];this.Ga=new Xa;this.Ga.md=q;this.Ga.e[s.b.Sc]=[0.5,0.5,0.5];this.Ga.e[s.b.Tc]=[0.5,0.5,0.5];this.Ga.e[s.b.yb]=
this.Gc;this.Ga.e[s.b.oc]=[2E3];this.Ma=[0.0390625,0.80859375,0];this.Gb=[0,0.60546875,0.58203125];this.ne=[0.99609375,0.44140625,0];this.nd=[0.98828125,0,0.0234375];this.F=new Ya(45,a.Za,0.1,4E3);J.set([383.349,12.549,-354.146],this.F.position);J.set([0.06,-12.009,0],this.F.rotation);this.ac=new Ya(45,a.Za,0.1,4E3);this.Ba=this.G=0;this.i=3;this.xa=1;this.Lc=this.la=this.s=this.Qa=this.U=0;this.Kb=[];this.pb=0;this.c=[];this.Ra=K.create();this.ma=new Za;this.Z=[];this.va=K.create();K.Pa(this.va);
K.translate(this.va,[196.7,4.5,-64.5]);K.rotate(this.va,0.807,[0,1,0]);this.Ea=aa();this.Pc=[];this.Mb=[];this.jc=this.ya=0}r=Ja.prototype;r.Le=function(a,b){this.F.Za=a/(0<b?b:1);this.F.$=m;this.ac.Za=a/(0<b?b:1);this.ac.$=m};
r.load=function(a){var b=1,c=this.a.ca,d=this.a.g,e=this,f,g;f=function(){b--;ca.innerHTML+=".";0===b&&"function"===typeof a?(a(),e.startTime=(new Date).getTime(),e.zg=new $a(e.l,d)):0>b&&u("Too much callbacks!","warn")};b++;Pa(c,"vignette",f);b++;Pa(c,"fade",f);b++;Pa(c,"normal",f);b++;Pa(c,"text",f);b++;Pa(c,"car",f);b++;Pa(c,"terrain",f);b++;Pa(c,"normal",f);b++;Pa(c,"multicol",f);b++;Pa(c,"multicolroad",f);b++;Pa(c,"sky",f);b++;Pa(c,"transparent",f);b++;Pa(c,"add",f);b++;Qa(c,"zemelapio_tex.jpg",
f);b++;Qa(c,"smelis_red.jpg",f);b++;Qa(c,"uola_blue.jpg",f);b++;Qa(c,"zole_green.jpg",f);b++;Qa(c,"kelias.png",f);b++;Qa(c,"betonas_red.jpg",f);b++;Qa(c,"sonas_asfalt_green.png",f);b++;Qa(c,"asphalt.jpg",f);b++;Qa(c,"water.jpg",f);b++;Qa(c,"dangus.jpg",f);b++;Sa(c,"isl.obj",m,f);b++;Sa(c,"road.obj",m,f);b++;Sa(c,"prpl.obj",m,f);b++;Sa(c,"water.obj",m,f);b++;Sa(c,"vsky.obj",q,f);b++;Sa(c,"b3.obj",q,f);b++;Sa(c,"arosa.obj",q,f);b++;c.dc["title.obj"]=new ab(c.d,"obj/title.obj",f);b++;ka(d,"roll.wav",
f);b++;ka(d,"offlow.ogg",f);b++;ka(d,"offmid.ogg",f);b++;ka(d,"offhigh.ogg",f);b++;ka(d,"onlow.ogg",f);b++;ka(d,"onmid.ogg",f);b++;ka(d,"onhigh.ogg",f);g=new L(I(c,"isl.obj"),B(c,"multicol"));g.tb=G(c,"zemelapio_tex.jpg");g.ub=G(c,"uola_blue.jpg");g.vb=G(c,"zole_green.jpg");g.Rc=G(c,"smelis_red.jpg");this.h.add(g);g=new L(I(c,"road.obj"),B(c,"multicolroad"));g.tb=G(c,"kelias.png");g.ub=G(c,"betonas_red.jpg");g.vb=G(c,"sonas_asfalt_green.png");g.Rc=G(c,"asphalt.jpg");this.h.add(g);g=new L(I(c,"prpl.obj"),
B(c,"terrain"));g.tb=G(c,"betonas_red.jpg");g.e[s.b.qc]=[40];this.h.add(g);g=new L(I(c,"vsky.obj"),B(c,"sky"));g.tb=G(c,"dangus.jpg");this.h.add(g);g=new L(I(c,"water.obj"),B(c,"water"));g.tb=G(c,"water.jpg");g.e[s.b.qc]=[100];this.h.add(g);for(g=0;7>g;g++)this.c[g]=new L(I(c,"title.obj"),B(c,"text")),this.c[g].e[s.b.p]=[0,0,0],J.set(this.Ma,this.c[g].e[s.b.p]),this.c[g].e[s.b.pc]=[0],this.c[g].text="xoxoxox",this.c[g].o[1]=-0.35*g,this.Ga.add(this.c[g]);M(this,0);for(g=0;3>g;g++)this.Z[g]=new L(I(c,
"title.obj"),B(c,"text")),this.Z[g].e[s.b.p]=[0,0,0],J.set(this.ne,this.Z[g].e[s.b.p]),this.Z[g].e[s.b.pc]=[0],this.Z[g].text="xoxoxox",this.Z[g].o[1]=-0.35*g,this.Ga.add(this.Z[g]);this.ma.bb.push(I(c,"road.obj"));this.ma.bb.push(I(c,"isl.obj"));this.ma.bb.push(I(c,"prpl.obj"));this.ma.bb.push(I(c,"water.obj"));I(c,"road.obj").Ob=0;I(c,"isl.obj").Ob=1;I(c,"prpl.obj").Ob=0;b++;V(this,"obj/obj.obj",f);b++;V(this,"obj/sviestuvai.obj",f);b++;V(this,"obj/kont.obj",f);b++;V(this,"obj/loc_laivas.obj",f);
b++;V(this,"obj/loc_hotel.obj",f);b++;V(this,"obj/loc_dangoraizis.obj",f);b++;V(this,"obj/loc_dangoraizis2.obj",f);b++;V(this,"obj/loc_didelis_namas.obj",f);b++;V(this,"obj/loc_siena.obj",f);b++;V(this,"obj/loc_tvora.obj",f);b++;V(this,"obj/loc_namas1.obj",f);b++;V(this,"obj/loc_namas2.obj",f);b++;V(this,"obj/loc_namas3.obj",f);b++;V(this,"obj/loc_namas4.obj",f);b++;V(this,"obj/loc_palme1.obj",f);b++;V(this,"obj/loc_svyturys.obj",f);b++;V(this,"obj/loc_pastatas1.obj",f);b++;V(this,"obj/loc_villa1.obj",
f);b++;V(this,"obj/loc_perkunas.obj",f);b++;V(this,"obj/loc_villa2.obj",f);b++;V(this,"obj/loc_villa.obj",f);b++;V(this,"obj/loc_lektuvas.obj",f);b++;V(this,"obj/loc_angaras.obj",f);b++;V(this,"obj/loc_ktu.obj",f);f()};r.Vc=function(a){"function"===typeof a&&a()};
function V(a,b,c){s.sd(b,function(d){var e,f,g=[],h=a.a.ca,j=J.create(),k="",d=d.split("\n");for(f=0;f<d.length;f++)if(0!==d[f].length&&(e=d[f].split(" "),0!==e.length))switch(e[0]){case "g":k=e[1].split(".")[0];break;case "v":4===e.length?(e=[parseFloat(e[1]),parseFloat(e[2]),parseFloat(e[3])],!isNaN(e[0])&&!isNaN(e[1])&&!isNaN(e[2])?g.push(e):i(Error("Bad vertex data in "+b+":"+f))):i(Error("Wrong vertex data count in "+b+":"+f));break;case "f":if(4===e.length)if(e=[parseInt(e[1],10),parseInt(e[2],
10),parseInt(e[3],10)],!isNaN(e[0])&&!isNaN(e[1])&&!isNaN(e[2])){k=k.replace("_Plane","");switch(k){case "loc_angaras":e=new L(I(h,"angaras.obj"),B(h,"terrain"),G(h,"angaras.jpg"));e.K=500;a.h.add(e);break;case "loc_ktu":e=new L(I(h,"tktu.obj"),B(h,"terrain"),G(h,"ktu.jpg"));e.K=1E3;a.h.add(e);break;case "loc_medis1":e=new L(I(h,"medis.obj"),B(h,"transparent"),G(h,"medis.png",q,m));e.Ja=m;e.Na=q;e.K=500;a.h.add(e,m);break;case "loc_palme1":e=new L(I(h,"palme1.obj"),B(h,"transparent"),G(h,"palme1.png",
q,m));e.Ja=m;e.Na=q;e.K=500;a.h.add(e,m);break;case "loc_sviestuvas":e=new L(I(h,"sviestuvas.obj"),B(h,"terrain"),G(h,"sviestuvas.jpg"));e.K=300;a.h.add(e);break;case "loc_kont":e=new L(I(h,"konteineris.obj"),B(h,"terrain"),G(h,"konteineris.jpg"));e.K=500;a.h.add(e);break;case "loc_laivas":e=new L(I(h,"laivas.obj"),B(h,"terrain"),G(h,"laivas.png"));a.h.add(e);break;case "loc_hotel":e=new L(I(h,"hotel.obj"),B(h,"terrain"),G(h,"hotel.jpg"));a.h.add(e);break;case "loc_dangoraizis":e=new L(I(h,"dangoraizis.obj"),
B(h,"add"),G(h,"dangoraizis.png",q));e.ub=G(h,"dangoraizis_add.png",q);e.vb=G(h,"dangus.jpg",q);e.e[s.b.p]=[0,0,0];a.h.add(e);break;case "loc_dangoraizis2":e=new L(I(h,"dangoraizis2.obj"),B(h,"terrain"),G(h,"dangoraizis2.png",q));a.h.add(e);break;case "loc_didelis_namas":e=new L(I(h,"didelis_namas.obj"),B(h,"terrain"),G(h,"didelis_namas.jpg"));a.h.add(e);break;case "loc_siena":e=new L(I(h,"siena.obj"),B(h,"terrain"),G(h,"siena.jpg"));a.h.add(e);e.K=200;break;case "loc_namas1":e=new L(I(h,"namas1.obj"),
B(h,"terrain"),G(h,"namas1.jpg"));e.K=1E3;a.h.add(e);break;case "loc_namas2":e=new L(I(h,"namas2.obj"),B(h,"terrain"),G(h,"namas2.jpg"));e.K=1E3;a.h.add(e);break;case "loc_tvora":e=new L(I(h,"tvora.obj"),B(h,"transparent"),G(h,"tvora.png",q,m));e.Ja=m;e.Na=q;e.K=200;a.h.add(e,m);break;case "loc_namas3":e=new L(I(h,"namas3.obj"),B(h,"terrain"),G(h,"namas3.jpg"));e.K=1E3;a.h.add(e);break;case "loc_namas4":e=new L(I(h,"namas4.obj"),B(h,"terrain"),G(h,"namas4.jpg"));e.K=1E3;a.h.add(e);break;case "loc_svyturys":e=
new L(I(h,"svyturys.obj"),B(h,"terrain"),G(h,"svyturys.png"));e.K=1E3;a.h.add(e);break;case "loc_perkunas":e=new L(I(h,"perkunas.obj"),B(h,"terrain"),G(h,"perkunas.jpg"));e.K=500;a.h.add(e);break;case "loc_pastatas1":e=new L(I(h,"pastatas1.obj"),B(h,"terrain"),G(h,"pastatas1.jpg"));a.h.add(e);break;case "loc_villa":e=new L(I(h,"villa.obj"),B(h,"terrain"),G(h,"villa.jpg"));e.K=500;a.h.add(e);break;case "loc_villa1":e=new L(I(h,"villa1.obj"),B(h,"terrain"),G(h,"villa1.jpg"));e.K=500;a.h.add(e);break;
case "loc_villa2":e=new L(I(h,"villa2.obj"),B(h,"terrain"),G(h,"villa2.jpg"));e.K=500;a.h.add(e);break;case "loc_lektuvas":e=new L(I(h,"lektuvas.obj"),B(h,"terrain"),G(h,"lektuvas.jpg"));e.K=500;a.h.add(e);break;default:u('Unknown object name "'+k+'"',"warn");g=[];continue}J.set(g[0],e.o);J.za(g[0],g[1],j);var o=J.length(j),n=Math.atan(j[0]/j[2]);0<j[2]&&(n+=Math.PI);e.K*=e.K;if("loc_palme1"===k||"loc_medis1"===k)o*=2;K.Pa(e.w);K.translate(e.w,g[0]);K.rotate(e.w,n-Math.PI/2,[0,1,0]);K.Pb(e.w,e.ba);
Y.xb(e.ba);K.scale(e.w,[o,o,o]);e.$=q;g=[]}else i(Error("Bad vertex data in "+b+":"+f));else i(Error("Wrong face data count in "+b+":"+f))}"function"===typeof c&&c()})}
function M(a,b){switch(b){case 0:a.c[0].text="webgl driver";J.set(a.ne,a.c[0].e[s.b.p]);a.c[1].text="user: "+a.Wa;a.c[2].text="pass: "+Array(a.Ua.length+1).join("*");a.c[3].text="login>";a.c[4].text="register>";a.c[5].text="options>";a.c[6].text="";J.set(a.nd,a.c[6].e[s.b.p]);break;case 1:a.c[0].text="options";a.c[1].text="sound "+s.gc(Math.floor(10*a.a.Db).toString(),4);a.c[2].text="video "+s.gc(Math.floor(10*a.a.Ka).toString(),4);a.c[3].text="fov   "+(a.a.Ib?"  on":" off");a.c[4].text="render "+
s.gc(a.a.Fa.toString(),3);a.c[5].text="<back";a.c[6].text="";break;case 2:a.c[0].text="game menu";a.c[1].text="continue";a.c[2].text="options";a.c[3].text="main menu";a.c[4].text="";a.c[5].text="";a.c[6].text="";break;case 3:a.c[0].text="choose your car";a.c[1].text="<name>";a.c[2].text="";a.c[3].text="";a.c[4].text="";a.c[5].text="";a.c[6].text="";break;default:a.c[0].text="",a.c[1].text="",a.c[2].text="",a.c[3].text="",a.c[4].text="",a.c[5].text="",a.c[6].text=""}}
function bb(a,b,c){var d,e,f;f=y(b,b.Jd)||A(b,b.If)||y(b,b.yf);var g=y(b,b.Sd)||A(b,b.Nf),h=y(b,b.sc)||A(b,b.Xd);d=y(b,b.tc)||A(b,b.Yd);e=y(b,b.Kd)||A(b,b.Vd);var j=y(b,b.Yc)||A(b,b.Wd),k=y(b,b.Nd)||A(b,b.Of);if(a.a.z===a.a.zb){-1===a.G&&j&&(a.G=2,M(a,a.G),a.i=-1,a.xa=1,a.s=-3,a.Ea=p,a.a.g.play("roll.wav"));if(2===a.G&&0===a.s){f&&(a.i++,4<=a.i&&(a.i=1),a.a.g.play("roll.wav"));g&&(a.i--,0>=a.i&&(a.i=3),a.a.g.play("roll.wav"));if(1===a.i&&e||j)a.Ba=-1,a.s=3,a.a.g.play("roll.wav");if(2===a.i&&(e||d))a.Ba=
1,a.xa=1,a.s=1,a.a.g.play("roll.wav");3===a.i&&e&&(a.a.g.play("roll.wav"),cb(a))}k&&(u("logout"),a.a.g.play("roll.wav"),xa&&xa.close())}0===a.G&&(1!==a.i&&2!==a.i&&0===a.s&&a.a.z===a.a.Aa&&j)&&(a.Ba=-1,a.s=3,a.xa=3,a.Ea=p,a.a.g.play("roll.wav"));-1===a.G&&(0===a.s&&a.a.z===a.a.Aa&&j)&&(a.G=0,M(a,a.G),a.i=-1,a.xa=3,a.s=-3,a.a.g.play("roll.wav"));if(0===a.G&&0===a.s&&a.a.z===a.a.Aa){f&&(a.i++,6<=a.i&&(a.i=1),a.a.g.play("roll.wav"));g&&(a.i--,0>=a.i&&(a.i=5),a.a.g.play("roll.wav"));1===a.i&&(f=qa(b,
a.Wa),f!==a.Wa&&(a.a.g.play("roll.wav"),10<f.length&&(f=f.slice(0,10)),a.Wa=f,a.c[1].text="user: "+a.Wa));2===a.i&&(f=qa(b,a.Ua),f!==a.Ua&&(a.a.g.play("roll.wav"),16<f.length&&(f=f.slice(0,16)),a.Ua=f,a.c[2].text="pass: "+Array(a.Ua.length+1).join("*")));if((1===a.i||2===a.i||3===a.i)&&e&&a.a.z===a.a.Aa)a.a.g.play("roll.wav"),2===ya?""===a.Wa||""===a.Ua?a.c[6].text="enter fields":(Ga("LOG "+a.Wa+" "+a.Ua),a.a.z=a.a.Zc,a.c[6].text="logging in"):(a.c[6].text="server offline =\\",2>a.Fe?(a.Fe++,3===
ya&&za(a.a.We)):(a.c[6].text="fine, ok, go play",a.a.id=43,b=new db(-1),b.ma=a.ma,f=new eb(b,a.a.ca,a.debug),g=new $a(b,a.a.g),a.h.add(f),a.a.$a.push(b),a.a.La.push(f),a.a.jb.push(g),a.a.H[43]={},a.a.H[43].l=b,a.a.H[43].Ic=f,a.a.H[43].g=g,a.a.z=a.a.zb,a.Ba=-1,a.s=3,a.Ea=function(){a.la=1}));4===a.i&&(e&&a.a.z===a.a.Aa)&&(a.a.g.play("roll.wav"),2===ya?""===a.Wa||""===a.Ua?a.c[6].text="enter fields":(Ga("REG "+a.Wa+" "+a.Ua),a.a.z=a.a.Zd,a.c[6].text="registering in"):a.c[6].text="server offline =\\");
if(5===a.i&&(e||d))a.s=1,a.Ba=1,a.xa=1,a.a.g.play("roll.wav")}else if(1===a.G&&0===a.s){f&&(a.i++,6<=a.i&&(a.i=1),a.a.g.play("roll.wav"));g&&(a.i--,0>=a.i&&(a.i=5),a.a.g.play("roll.wav"));1===a.i&&h&&(ia(a.a.g,ja(a.a.g)-0.1),a.a.Db=ja(a.a.g),a.a.g.play("roll.wav"),M(a,1));1===a.i&&d&&(ia(a.a.g,ja(a.a.g)+0.1),a.a.Db=ja(a.a.g),a.a.g.play("roll.wav"),M(a,1));2===a.i&&h&&(a.a.Ka=Math.floor(10*s.sa(a.a.Ka-0.1,0.1,2.6)+0.01)/10,a.a.Ec(),a.a.g.play("roll.wav"),M(a,1));2===a.i&&d&&(a.a.Ka=Math.floor(10*s.sa(a.a.Ka+
0.1,0.1,2.6)+0.01)/10,a.a.Ec(),a.a.g.play("roll.wav"),M(a,1));if(3===a.i&&(h||d||e))a.a.Ib=!a.a.Ib,a.a.g.play("roll.wav"),M(a,1);4===a.i&&h&&(a.a.Fa--,1>a.a.Fa&&(a.a.Fa=1),a.a.g.play("roll.wav"),M(a,1));4===a.i&&d&&(a.a.Fa++,10<a.a.Fa&&(a.a.Fa=10),a.a.g.play("roll.wav"),M(a,1));if(j||5===a.i&&(e||h))a.a.z===a.a.Aa?(a.G=0,a.xa=5):a.a.z===a.a.zb&&(a.G=2,a.xa=2),a.s=-1,a.a.g.play("roll.wav")}1===a.s&&(a.U+=20*c,5<=a.U&&(a.G=a.Ba,M(a,a.G),a.i=-1,a.U=-5,a.s=2));2===a.s&&(a.U+=20*c,0<a.U&&(a.i=a.xa,a.U=
0,a.s=0));-1===a.s&&(a.U-=20*c,-5>=a.U&&(M(a,a.G),a.i=-1,a.s=-2,a.U=5));-2===a.s&&(a.U-=20*c,0>a.U&&(a.i=a.xa,a.U=0,a.s=0));3===a.s&&(a.Qa+=10*c,2<a.Qa&&(a.s=0,a.G=a.Ba,M(a,a.Ba),"function"===typeof a.Ea&&a.Ea()));-3===a.s&&(a.Qa-=10*c,0>a.Qa&&(a.i=a.xa,a.Qa=0,a.s=0));K.Pa(a.Ra);K.translate(a.Ra,[-1.8,0.8,-3.5]);K.rotate(a.Ra,-1.02,[0,1,0]);(2===a.G||1===a.G&&a.a.z===a.a.zb)&&K.scale(a.Ra,[0.5,0.5,0.5]);a.a.z===a.a.uc&&(K.Pa(a.Ra),K.translate(a.Ra,[-1.8,1.2,-3.5]),K.rotate(a.Ra,-1.02,[0,1,0]),K.scale(a.Ra,
[0.5,0.5,0.5]));e=p;for(d=a.c.length-1;0<=d;d--)e=a.c[d],a.i===d?0.1>e.o[0]&&(e.o[0]+=0.6*c,0.1<e.o[0]&&(e.o[0]=0.1),e.e[s.b.p][0]=a.Ma[0]*(1-10*e.o[0])+a.Gb[0]*10*e.o[0],e.e[s.b.p][1]=a.Ma[1]*(1-10*e.o[0])+a.Gb[1]*10*e.o[0],e.e[s.b.p][2]=a.Ma[2]*(1-10*e.o[0])+a.Gb[2]*10*e.o[0]):0<e.o[0]&&(e.o[0]-=0.6*c,0>e.o[0]&&(e.o[0]=0),e.e[s.b.p][0]=a.Ma[0]*(1-10*e.o[0])+a.Gb[0]*10*e.o[0],e.e[s.b.p][1]=a.Ma[1]*(1-10*e.o[0])+a.Gb[1]*10*e.o[0],e.e[s.b.p][2]=a.Ma[2]*(1-10*e.o[0])+a.Gb[2]*10*e.o[0]),K.set(a.Ra,e.w),
K.translate(e.w,e.o),K.translate(e.w,[0,Math.pow(a.Qa,2)*s.rb(a.Qa),Math.pow(a.U,2)*s.rb(a.U)]),K.Pb(e.w,e.ba),Y.xb(e.ba),0===d&&K.scale(e.w,[1.2,1.2,1.2]);a.a.H[a.a.id]?(b=a.a.H[a.a.id].l,c=3.6*((b.j[1].S*b.j[1].Lb+b.j[0].S*b.j[0].Lb)/2),a.Z[0].ua=m,a.Z[1].ua=m,a.Z[2].ua=q,a.Z[0].text=s.gc(Math.abs(Math.floor(c))+" KPH",7),a.Z[1].text=s.gc(Math.floor(30*b.aa.L/Math.PI)+" "+["N","1","2","3","4","5","6",,,,"R"][b.M].toString(),7)):(a.Z[0].ua=q,a.Z[1].ua=q,a.Z[2].ua=q);K.Pa(a.va);K.translate(a.va,[0.96,
-0.8,-3.5]);K.rotate(a.va,-2,[0,1,0]);K.scale(a.va,[0.5,0.5,0.5]);for(d=a.Z.length-1;0<=d;d--)e=a.Z[d],e.ua&&(K.set(a.va,e.w),K.translate(e.w,e.o),K.Pb(e.w,e.ba),Y.xb(e.ba))}r.xd=function(){this.la=1};
function cb(a){console.log("logout");Ga("OUT");var b,c;for(b in a.a.H)a.a.H.hasOwnProperty(b)&&(c=a.a.H[b],c!==p&&(fb(c.Ic,a.h),c.g.remove(),a.a.Oc[b]=a.u));a.a.$a.length=0;a.a.La.length=0;a.a.jb.length=0;a.a.H={};a.a.id=-1;a.Ba=-1;a.s=3;a.la=0;a.Ea=function(){this.G=0;M(this,this.G);this.i=-1;this.xa=3;this.s=-3;this.Ea=p;this.a.z=this.a.Aa}}
r.update=function(a,b){var c=(b-this.time)/1E3;0.1<c?(c=Math.floor((c-this.ab)/this.ab),console.log("Skipping "+c+" frames"),this.u+=c,c=this.ab,this.hb=0):0>c&&(c=0);this.time=b;this.hb+=c;var d,e=this.a.H[this.a.id]&&this.a.H[this.a.id].l;this.a.Ze(this.F,a,c,z(a,a.wf)?20:200);this.a.z===this.a.Aa&&this.a.$e(this.F,a,c);if((1===this.la||2===this.la)&&-1===this.G&&e)if(this.a.Vf(e,a),A(a,a.Hf)||y(a,a.Qd))console.log("but"),Ga("RST"),3===ya&&(e.Q[1]=this.ma.rc(e.Q[0],e.Q[2]).cb+1,J.set([0,0,0],e.fa),
Z.set([0,0.554,0,0.832],e.J),J.set([0,0,0],e.qa),e.j[0].S=0.001,e.j[1].S=0.001,e.j[2].S=0.001,e.j[3].S=0.001);if(A(a,a.Jf)||y(a,a.Od)){this.debug=!this.debug;for(d=0;d<this.a.La.length;d++){var f=this.a.La[d],g=this.debug,h=l;if(g===m){0===f.k.length&&gb(f);for(h=f.k.length-1;0<=h;h--)f.k[h].ua=m;f.$b=m}else if(g===q){for(h=f.k.length-1;0<=h;h--)f.k[h].ua=q;f.$b=q}}}if(1===this.la||2===this.la)if(A(a,a.Lf)||y(a,a.Hd))this.la=1===this.la?2:1;if(2===ya){var j,k,f=va;va=[];g=f.length;for(d=0;d<g;d++)if(j=
f[d],"string"!==typeof j)a:{k=j;j=l;var o=new Uint8Array(k,0,12);j=(new Uint32Array(k,4,1))[0];if(67===o[0]&&68===o[1]){var n=256*o[2]+o[3],h=p;if(!this.a.H[n]){if(this.a.Oc[n]&&this.a.Oc[n]+500>this.u){console.log("Dead car driving "+n);break a}console.log("NEW car "+n);h=new db(o[8]);h.ma=this.ma;var o=new eb(h,this.a.ca,this.debug),t=new $a(h,this.a.g);this.h.add(o);this.a.$a.push(h);this.a.La.push(o);this.a.jb.push(t);this.a.H[n]={};this.a.H[n].l=h;this.a.H[n].Ic=o;this.a.H[n].g=t}h=this.a.H[n].l;
if(n!==this.a.id&&(j+=120,j>this.u)){h.Ne.push({u:j,state:k});break a}if(!(400<this.u-j)){h.setData(k,8);k=h.Dc;for(n=0;k[0]&&k[0].u<j;)k.shift();for(;j<this.u;j++)k[n]&&k[n].u===j&&(h.C=k[n].C,h.v=k[n].v,h.t=k[n].t,n++),hb(h,this.ab)}}}else switch(h=j.split(" "),h[0]){case "HI!":break;case "HID":this.a.id=parseInt(h[1],10);console.log("New ID: "+this.a.id);break;case "LOG":if(this.a.z!==this.a.Zc){console.log("Server LOG message not in place!");continue}"SUC"===h[1]?(this.c[6].text="Logged in!",
J.set(this.Ma,this.c[6].e[s.b.p]),this.a.z=this.a.zb,this.Ba=-1,this.s=3,this.Ea=this.xd,this.a.g.play("roll.wav")):(this.c[6].text=h.slice(2).join(" ").slice(0,16).toLowerCase(),J.set(this.nd,this.c[6].e[s.b.p]),this.a.z=this.a.Aa);break;case "REG":if(this.a.z!==this.a.Zd){console.log("Server REG message not in place!");continue}"SUC"===h[1]?(this.c[6].text="Registered!",J.set(this.Ma,this.c[6].e[s.b.p]),this.a.z=this.a.Zc,this.Ba=-1,this.s=3,this.Ea=this.xd,this.a.g.play("roll.wav")):(this.c[6].text=
h.slice(2).join(" ").slice(0,16).toLowerCase(),J.set(this.nd,this.c[6].e[s.b.p]),this.a.z=this.a.Aa);break;case "POG":this.Kb.push((new Date).getTime()-this.Lc);if(20>this.Kb.length)this.Lc=(new Date).getTime(),Ga("PIG");else if(20===this.Kb.length){this.pb=0;for(h=this.Kb.length-1;0<=h;h--)this.pb+=this.Kb[h];this.pb=Math.ceil(this.pb/this.Kb.length);Ga("SIF")}break;case "SIF":console.log("Synchronizing time with server "+h[1]);this.u=parseInt(h[1],10)+Math.ceil(1.3*this.pb/2);break;case "OUT":j=
parseInt(h[1],10);k=this.a.H[j];console.log("OUT "+j);k&&(fb(k.Ic,this.h),k.g.remove(),this.a.$a.splice(this.a.$a.indexOf(k.l),1),this.a.La.splice(this.a.La.indexOf(k.Ic),1),this.a.jb.splice(this.a.jb.indexOf(k.g),1),this.a.H[j]=p,this.a.Oc[j]=this.u);break;case "CNT":j=parseInt(h[1],10);k=this.a.H[j];if(!k)continue;j=this.a.H[j].l;k=this.u-120;parseInt(h[2],10)<k?console.log("PC controll frame came "+(k-parseInt(h[2],10))+" frames too late"):j.Dc.push({u:parseInt(h[2],10)+120,C:parseFloat(h[3]),
v:parseFloat(h[4]),t:parseFloat(h[5])});break;case "LAG":console.log("High ping, slowing down");this.u+=1;break;case "GBC":console.log("Go buy a car");j=h=l;J.set([-312.256,1.68,18.914],this.F.position);J.set([-0.1,-2.59,0],this.F.rotation);this.F.$=m;this.jc=0;this.a.z=this.a.uc;j=[1,2,3,4,5,6,9,11];n=k=p;for(h=0;h<j.length;h++)k=new db(j[h]),k.ma=this.ma,J.set([-298.39-8*h,0.388,25.159-0.3*h],k.Q),n=new eb(k,this.a.ca,this.debug),this.h.add(n),this.Pc.push(k),this.Mb.push(n);for(h=0;400>h;h++)for(j=
0;j<this.Pc.length;j++)hb(this.Pc[j],this.a.eg);this.G=3;M(this,this.G);this.xa=1;this.s=-3;break;case "BOK":this.a.z=this.a.zb;this.G=-1;this.s=3;this.Ea=this.xd();h=l;for(h=this.Mb.length-1;0<=h;h--)fb(this.Mb[h],this.h);this.Mb.length=0;this.Pc.length=0;break;default:console.log("Unknown message form server "+j)}0===this.Lc&&(this.Lc=(new Date).getTime(),Ga("PIG"))}if(this.a.z===this.a.uc){d=c;g=y(a,a.sc)||A(a,a.Xd);h=y(a,a.tc)||A(a,a.Yd);j=y(a,a.Kd)||A(a,a.Vd);k=y(a,a.Yc)||A(a,a.Wd);f=J.create();
if(0===this.jc)g&&(this.ya--,0>this.ya&&(this.ya=7),this.a.g.play("roll.wav")),h&&(this.ya++,7<this.ya&&(this.ya=0),this.a.g.play("roll.wav")),j&&(this.jc=1),this.c[1].text="<"+"Guolen B3;Ring Alpha;Gunter ULF;Hamer Head;Takamura F35;Biattino Arosa;Beat R500;Admin car".split(";")[this.ya]+">",this.c[2].text="price:"+"22,000;21,000;25,000;92,300;52,000;100,000;60,000;over 9000".split(";")[this.ya]+"\u20ac",this.c[3].text="";else if(1===this.jc&&(this.c[3].text="Are you shure?",k&&(this.jc=0,this.a.g.play("roll.wav")),
j))g=[1,2,3,4,5,6,9,11],console.log("BUY "+g[this.ya]),Ga("BUY "+g[this.ya]),this.a.g.play("roll.wav");f[0]=-312.256+-8*(this.ya-1);f[1]=1.68;f[2]=18.914+-0.3*(this.ya-1);g=this.F;h=0;h=20*J.qe(g.position,f);J.direction(g.position,f,g.nc);s.Da.Cb(g.L,g.nc,-h*d);J.scale(g.L,0.8);s.Da.Cb(g.position,g.L,d);g.$=m;this.F.$=m}for(;this.hb>=this.ab;){this.hb-=this.ab;if(e&&2===ya&&(this.a.Ie!==e.C||this.a.He!==e.v||this.a.Ge!==e.t))d="CNT "+this.u+" "+e.C+" "+e.v+" "+e.t,Ga(d),d=d.split(" "),e.Dc.push({u:parseInt(d[1],
10),C:parseFloat(d[2]),v:parseFloat(d[3]),t:parseFloat(d[4])}),e.C=parseFloat(d[2]),e.v=parseFloat(d[3]),e.t=parseFloat(d[4]),this.a.Ie=e.C,this.a.He=e.v,this.a.Ge=e.t;for(d=0;d<this.a.$a.length;d++){f=this.a.$a[d];if(e!==f&&(h=f.Dc,g=f.Ne,h[0]&&(h[0].u===this.u?(h=h.shift(),f.C=h.C,f.v=h.v,f.t=h.t):h[0].u<this.u&&h.shift()),g[0]))if(g[0].u===this.u){g=g.shift();f.setData(g.state,8);continue}else g[0].u<this.u&&g.shift();hb(this.a.$a[d],this.ab)}1===this.la&&this.a.H[this.a.id]&&(d=this.F,f=this.a.H[this.a.id].l.Q,
g=this.ab,h=h=0,h=J.qe(d.position,f),h=40*(h-7),J.direction(d.position,f,d.nc),s.Da.Cb(d.L,d.nc,-h*g),J.scale(d.L,0.98),s.Da.Cb(d.position,d.L,g),d.position[1]=f[1]+2,d.$=m);this.u++}for(d=0;d<this.a.La.length;d++)ib(this.a.La[d]);1===this.la&&e&&this.F.Ae(e.Q[0],e.Q[1]+0.5,e.Q[2]);2===this.la&&e&&(d=K.create(),K.Je(this.F.ue,this.F.Za,this.F.De,this.F.mb,d),K.translate(d,[0,-0.93,0.59]),K.multiply(d,e.bc,this.F.Ca),J.set(e.Q,this.F.position),this.F.e[s.b.Bd]=[e.Q[0],e.Q[1],e.Q[2]],this.$=q);if(this.a.z===
this.a.uc)for(d=0;d<this.Mb.length;d++)ib(this.Mb[d]);bb(this,a,c);1===this.la&&e&&(K.set(e.bc,this.va),K.translate(this.va,[-1.5,-0.8,3.5]),K.rotate(this.va,1.15,[0,1,0]),K.scale(this.va,[0.5,0.5,0.5]));c=0.001*(this.time-1337462504954);e=Math.sin(5.0E-4*c);d=Math.cos(5.0E-4*c);this.h.e[s.b.Ue][0]=c;this.Gc[0]=0.507*d-0.3*e;this.Gc[2]=0.507*e+0.3*d;for(d=0;d<this.a.jb.length;d++)this.a.jb[d].update(this.F)};
r.qb=function(a){if(a.pd){var b=a.d,c,d;for(d in a.Oa)a.Oa.hasOwnProperty(d)&&(c=a.Oa[d],c.width=a.width,c.height=a.height,b.bindFramebuffer(b.FRAMEBUFFER,c.Hb),b.bindTexture(b.TEXTURE_2D,c.ia),b.bindRenderbuffer(b.RENDERBUFFER,c.Nc),b.texImage2D(b.TEXTURE_2D,0,b.RGBA,c.width,c.height,0,b.RGBA,c.type,p),b.renderbufferStorage(b.RENDERBUFFER,b.DEPTH_COMPONENT16,c.width,c.height));b.bindTexture(b.TEXTURE_2D,p);b.bindRenderbuffer(b.RENDERBUFFER,p);b.bindFramebuffer(b.FRAMEBUFFER,p);a.pd=q}if(this.a.Ib===
m){a.d.bindFramebuffer(a.d.FRAMEBUFFER,Ia(a,"scene").Hb);a.qb(this.h,this.F);a.d.clear(a.d.DEPTH_BUFFER_BIT);a.qb(this.Ga,this.ac);a.d.bindFramebuffer(a.d.FRAMEBUFFER,Ia(a,"depth").Hb);a.d.clear(a.d.COLOR_BUFFER_BIT|a.d.DEPTH_BUFFER_BIT);Na(a,this.h,this.F);Na(a,this.Ga,this.ac);b=Ia(a,"scene");c=Ia(a,"depth");var e=this.a.focus,f=1/1024;d=a.d;var g=B(a,"vgauss"),h=B(a,"hgauss"),j=Ia(a,"tgauss"),f="number"===typeof f?f:1/512,e="number"===typeof e?e:0.25;g.W&&h.W&&(d.bindFramebuffer(d.FRAMEBUFFER,
j.Hb),d.useProgram(g.ea),a.ib=g,Wa(g,"aVerPosition",a.Wb,3),g.bindTexture(0,b.ia),g.bindTexture(1,c.ia),d.uniform1i(g.ja[g.pa.indexOf(s.b.Rb)],0),d.uniform1i(g.ja[g.pa.indexOf(s.b.Uc)],1),d.uniform1f(g.ja[g.pa.indexOf(s.b.Pe)],f),d.uniform1f(g.ja[g.pa.indexOf(s.b.Re)],e),d.disable(d.DEPTH_TEST),d.drawArrays(d.TRIANGLES,0,6),d.bindFramebuffer(d.FRAMEBUFFER,p),d.useProgram(h.ea),a.ib=h,Wa(h,"aVerPosition",a.Wb,3),d.activeTexture(d.TEXTURE0),d.bindTexture(d.TEXTURE_2D,j.ia),d.uniform1i(h.ja[h.pa.indexOf(s.b.Rb)],
0),d.uniform1i(h.ja[h.pa.indexOf(s.b.Uc)],1),d.uniform1f(h.ja[h.pa.indexOf(s.b.Pe)],f),d.uniform1f(h.ja[h.pa.indexOf(s.b.Re)],e),d.drawArrays(d.TRIANGLES,0,6),d.enable(d.DEPTH_TEST))}else a.qb(this.h,this.F),a.d.clear(a.d.DEPTH_BUFFER_BIT),a.qb(this.Ga,this.ac);b=a.d;c=B(a,"vignette");c.W&&(b.useProgram(c.ea),a.ib=c,Va(c,"aVerPosition"),Wa(c,"aVerPosition",a.Wb,3),b.enable(b.BLEND),b.disable(b.DEPTH_TEST),b.drawArrays(b.TRIANGLES,0,6),b.disable(b.BLEND),b.enable(b.DEPTH_TEST));1500>this.time-this.startTime&&
(b=Math.max(0,Math.min(1,(1500-this.time+this.startTime)/1500)),b=Math.pow(b,1.4),c=a.d,d=B(a,"fade"),b===l&&(b=0.5),d.W&&(c.useProgram(d.ea),a.ib=d,Wa(d,"aVerPosition",a.Wb,3),c.uniform1f(d.ja[d.pa.indexOf(s.b.Qe)],b),c.enable(c.BLEND),c.disable(c.DEPTH_TEST),c.drawArrays(c.TRIANGLES,0,6),c.disable(c.BLEND),c.enable(c.DEPTH_TEST)));this.Me++};var J={},Y={},K={},Z={},jb=p;typeof Float32Array!==l?jb=Float32Array:jb=Array;"undefined"!==typeof exports&&(global.Da=J,global.Eg=Y,global.Fg=K,global.ud=Z);J.create=function(a){var b=new jb(3);if(a===l)b[0]=b[1]=b[2]=0;else{b[0]=a[0];b[1]=a[1];b[2]=a[2]}return b};J.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b};J.add=function(a,b,c){if(!c||a===c){a[0]=a[0]+b[0];a[1]=a[1]+b[1];a[2]=a[2]+b[2];return a}c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c};
J.za=function(a,b,c){if(!c||a===c){a[0]=a[0]-b[0];a[1]=a[1]-b[1];a[2]=a[2]-b[2]}else{c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2]}};J.multiply=function(a,b,c){if(!c||a===c){a[0]=a[0]*b[0];a[1]=a[1]*b[1];a[2]=a[2]*b[2];return a}c[0]=a[0]*b[0];c[1]=a[1]*b[1];c[2]=a[2]*b[2];return c};J.Hg=function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b};J.scale=function(a,b,c){if(!c||a===c){a[0]=a[0]*b;a[1]=a[1]*b;a[2]=a[2]*b;return a}c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c};
J.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=Math.sqrt(c*c+d*d+e*e);if(!f){b[0]=0;b[1]=0;b[2]=0;return b}if(f===1){b[0]=c;b[1]=d;b[2]=e;return b}f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;return b};J.kb=function(a,b,c){c||(c=a);var d=a[0],e=a[1],a=a[2],f=b[0],g=b[1],b=b[2];c[0]=e*b-a*g;c[1]=a*f-d*b;c[2]=d*g-e*f;return c};J.length=function(a){var b=a[0],c=a[1],a=a[2];return Math.sqrt(b*b+c*c+a*a)};J.ga=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]};
J.direction=function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1],a=a[2]-b[2],b=Math.sqrt(d*d+e*e+a*a);if(!b){c[0]=0;c[1]=0;c[2]=0;return c}b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c};J.Dg=function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d};J.qe=function(a,b){var c=b[0]-a[0],d=b[1]-a[1],e=b[2]-a[2];return Math.sqrt(c*c+d*d+e*e)};
J.Sg=function(a,b,c,d,e){e||(e=a);var f=K.create(),g=new jb(4);g[0]=(a[0]-d[0])*2/d[2]-1;g[1]=(a[1]-d[1])*2/d[3]-1;g[2]=2*a[2]-1;g[3]=1;K.multiply(c,b,f);if(!K.inverse(f))return p;K.ig(f,g);if(g[3]===0)return p;e[0]=g[0]/g[3];e[1]=g[1]/g[3];e[2]=g[2]/g[3];return e};J.Qc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"};Y.create=function(a){var b=new jb(9);if(a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8]}return b};
Y.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b};Y.Pa=function(a){a||(a=Y.create());a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a};Y.xb=function(a,b){if(!b||a===b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b};
Y.zd=function(a,b){b||(b=K.create());b[15]=1;b[14]=0;b[13]=0;b[12]=0;b[11]=0;b[10]=a[8];b[9]=a[7];b[8]=a[6];b[7]=0;b[6]=a[5];b[5]=a[4];b[4]=a[3];b[3]=0;b[2]=a[2];b[1]=a[1];b[0]=a[0];return b};Y.Qc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"};
K.create=function(a){var b=new jb(16);if(a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15]}return b};K.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b};
K.Pa=function(a){a||(a=K.create());a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};
K.xb=function(a,b){if(!b||a===b){var c=a[1],d=a[2],e=a[3],f=a[6],g=a[7],h=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=f;a[11]=a[14];a[12]=e;a[13]=g;a[14]=h;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b};
K.Ag=function(a){var b=a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],h=a[6],j=a[7],k=a[8],o=a[9],n=a[10],t=a[11],w=a[12],v=a[13],C=a[14],a=a[15];return w*o*h*e-k*v*h*e-w*g*n*e+f*v*n*e+k*g*C*e-f*o*C*e-w*o*d*j+k*v*d*j+w*c*n*j-b*v*n*j-k*c*C*j+b*o*C*j+w*g*d*t-f*v*d*t-w*c*h*t+b*v*h*t+f*c*C*t-b*g*C*t-k*g*d*a+f*o*d*a+k*c*h*a-b*o*h*a-f*c*n*a+b*g*n*a};
K.inverse=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],j=a[6],k=a[7],o=a[8],n=a[9],t=a[10],w=a[11],v=a[12],C=a[13],F=a[14],N=a[15],W=c*h-d*g,X=c*j-e*g,O=c*k-f*g,P=d*j-e*h,Q=d*k-f*h,R=e*k-f*j,S=o*C-n*v,T=o*F-t*v,U=o*N-w*v,fa=n*F-t*C,ga=n*N-w*C,ha=t*N-w*F,H=W*ha-X*ga+O*fa+P*U-Q*T+R*S;if(!H)return p;H=1/H;b[0]=(h*ha-j*ga+k*fa)*H;b[1]=(-d*ha+e*ga-f*fa)*H;b[2]=(C*R-F*Q+N*P)*H;b[3]=(-n*R+t*Q-w*P)*H;b[4]=(-g*ha+j*U-k*T)*H;b[5]=(c*ha-e*U+f*T)*H;b[6]=(-v*R+F*O-N*X)*H;b[7]=(o*R-t*O+
w*X)*H;b[8]=(g*ga-h*U+k*S)*H;b[9]=(-c*ga+d*U-f*S)*H;b[10]=(v*Q-C*O+N*W)*H;b[11]=(-o*Q+n*O-w*W)*H;b[12]=(-g*fa+h*T-j*S)*H;b[13]=(c*fa-d*T+e*S)*H;b[14]=(-v*P+C*X-F*W)*H;b[15]=(o*P-n*X+t*W)*H;return b};K.Og=function(a,b){b||(b=K.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};
K.pg=function(a,b){b||(b=Y.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};K.Pb=function(a,b){var c=a[0],d=a[1],e=a[2],f=a[4],g=a[5],h=a[6],j=a[8],k=a[9],o=a[10],n=o*g-h*k,t=-o*f+h*j,w=k*f-g*j,v=c*n+d*t+e*w;if(v){v=1/v;b||(b=Y.create());b[0]=n*v;b[1]=(-o*d+e*k)*v;b[2]=(h*d-e*g)*v;b[3]=t*v;b[4]=(o*c-e*j)*v;b[5]=(-h*c+e*f)*v;b[6]=w*v;b[7]=(-k*c+d*j)*v;b[8]=(g*c-d*f)*v}};
K.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],g=a[3],h=a[4],j=a[5],k=a[6],o=a[7],n=a[8],t=a[9],w=a[10],v=a[11],C=a[12],F=a[13],N=a[14],a=a[15],W=b[0],X=b[1],O=b[2],P=b[3],Q=b[4],R=b[5],S=b[6],T=b[7],U=b[8],fa=b[9],ga=b[10],ha=b[11],H=b[12],Da=b[13],Ea=b[14],b=b[15];c[0]=W*d+X*h+O*n+P*C;c[1]=W*e+X*j+O*t+P*F;c[2]=W*f+X*k+O*w+P*N;c[3]=W*g+X*o+O*v+P*a;c[4]=Q*d+R*h+S*n+T*C;c[5]=Q*e+R*j+S*t+T*F;c[6]=Q*f+R*k+S*w+T*N;c[7]=Q*g+R*o+S*v+T*a;c[8]=U*d+fa*h+ga*n+ha*C;c[9]=U*e+fa*j+ga*t+ha*F;c[10]=
U*f+fa*k+ga*w+ha*N;c[11]=U*g+fa*o+ga*v+ha*a;c[12]=H*d+Da*h+Ea*n+b*C;c[13]=H*e+Da*j+Ea*t+b*F;c[14]=H*f+Da*k+Ea*w+b*N;c[15]=H*g+Da*o+Ea*v+b*a;return c};K.wa=function(a,b,c){c||(c=b);var d=b[0],e=b[1],b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};
K.ig=function(a,b){var c;c||(c=b);var d=b[0],e=b[1],f=b[2],g=b[3];c[0]=a[0]*d+a[4]*e+a[8]*f+a[12]*g;c[1]=a[1]*d+a[5]*e+a[9]*f+a[13]*g;c[2]=a[2]*d+a[6]*e+a[10]*f+a[14]*g;c[3]=a[3]*d+a[7]*e+a[11]*f+a[15]*g};
K.translate=function(a,b,c){var d=b[0],e=b[1],b=b[2],f,g,h,j,k,o,n,t,w,v,C,F;if(!c||a===c){a[12]=a[0]*d+a[4]*e+a[8]*b+a[12];a[13]=a[1]*d+a[5]*e+a[9]*b+a[13];a[14]=a[2]*d+a[6]*e+a[10]*b+a[14];a[15]=a[3]*d+a[7]*e+a[11]*b+a[15];return a}f=a[0];g=a[1];h=a[2];j=a[3];k=a[4];o=a[5];n=a[6];t=a[7];w=a[8];v=a[9];C=a[10];F=a[11];c[0]=f;c[1]=g;c[2]=h;c[3]=j;c[4]=k;c[5]=o;c[6]=n;c[7]=t;c[8]=w;c[9]=v;c[10]=C;c[11]=F;c[12]=f*d+k*e+w*b+a[12];c[13]=g*d+o*e+v*b+a[13];c[14]=h*d+n*e+C*b+a[14];c[15]=j*d+t*e+F*b+a[15];
return c};K.scale=function(a,b,c){var d=b[0],e=b[1],b=b[2];if(!c||a===c){a[0]=a[0]*d;a[1]=a[1]*d;a[2]=a[2]*d;a[3]=a[3]*d;a[4]=a[4]*e;a[5]=a[5]*e;a[6]=a[6]*e;a[7]=a[7]*e;a[8]=a[8]*b;a[9]=a[9]*b;a[10]=a[10]*b;a[11]=a[11]*b;return a}c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
K.rotate=function(a,b,c,d){var e=c[0],f=c[1],c=c[2],g=Math.sqrt(e*e+f*f+c*c),h,j,k,o,n,t,w,v,C,F,N,W,X,O,P,Q,R,S,T,U;if(!g)return p;if(g!==1){g=1/g;e=e*g;f=f*g;c=c*g}h=Math.sin(b);j=Math.cos(b);k=1-j;b=a[0];g=a[1];o=a[2];n=a[3];t=a[4];w=a[5];v=a[6];C=a[7];F=a[8];N=a[9];W=a[10];X=a[11];O=e*e*k+j;P=f*e*k+c*h;Q=c*e*k-f*h;R=e*f*k-c*h;S=f*f*k+j;T=c*f*k+e*h;U=e*c*k+f*h;e=f*c*k-e*h;f=c*c*k+j;if(d){if(a!==d){d[12]=a[12];d[13]=a[13];d[14]=a[14];d[15]=a[15]}}else d=a;d[0]=b*O+t*P+F*Q;d[1]=g*O+w*P+N*Q;d[2]=
o*O+v*P+W*Q;d[3]=n*O+C*P+X*Q;d[4]=b*R+t*S+F*T;d[5]=g*R+w*S+N*T;d[6]=o*R+v*S+W*T;d[7]=n*R+C*S+X*T;d[8]=b*U+t*e+F*f;d[9]=g*U+w*e+N*f;d[10]=o*U+v*e+W*f;d[11]=n*U+C*e+X*f;return d};
K.Kg=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[4],f=a[5],g=a[6],h=a[7],j=a[8],k=a[9],o=a[10],n=a[11];if(c){if(a!==c){c[0]=a[0];c[1]=a[1];c[2]=a[2];c[3]=a[3];c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15]}}else c=a;c[4]=e*b+j*d;c[5]=f*b+k*d;c[6]=g*b+o*d;c[7]=h*b+n*d;c[8]=e*-d+j*b;c[9]=f*-d+k*b;c[10]=g*-d+o*b;c[11]=h*-d+n*b;return c};
K.Lg=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],f=a[1],g=a[2],h=a[3],j=a[8],k=a[9],o=a[10],n=a[11];if(c){if(a!==c){c[4]=a[4];c[5]=a[5];c[6]=a[6];c[7]=a[7];c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15]}}else c=a;c[0]=e*b+j*-d;c[1]=f*b+k*-d;c[2]=g*b+o*-d;c[3]=h*b+n*-d;c[8]=e*d+j*b;c[9]=f*d+k*b;c[10]=g*d+o*b;c[11]=h*d+n*b;return c};
K.Mg=function(a,b,c){var d=Math.sin(b),b=Math.cos(b),e=a[0],f=a[1],g=a[2],h=a[3],j=a[4],k=a[5],o=a[6],n=a[7];if(c){if(a!==c){c[8]=a[8];c[9]=a[9];c[10]=a[10];c[11]=a[11];c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15]}}else c=a;c[0]=e*b+j*d;c[1]=f*b+k*d;c[2]=g*b+o*d;c[3]=h*b+n*d;c[4]=e*-d+j*b;c[5]=f*-d+k*b;c[6]=g*-d+o*b;c[7]=h*-d+n*b;return c};
K.dg=function(a,b,c,d,e,f,g){g||(g=K.create());var h=b-a,j=d-c,k=f-e;g[0]=e*2/h;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=e*2/j;g[6]=0;g[7]=0;g[8]=(b+a)/h;g[9]=(d+c)/j;g[10]=-(f+e)/k;g[11]=-1;g[12]=0;g[13]=0;g[14]=-(f*e*2)/k;g[15]=0};K.Je=function(a,b,c,d,e){a=c*Math.tan(a*Math.PI/360);b=a*b;K.dg(-b,b,-a,a,c,d,e)};
K.Jg=function(a,b,c,d,e,f,g){g||(g=K.create());var h=b-a,j=d-c,k=f-e;g[0]=2/h;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2/j;g[6]=0;g[7]=0;g[8]=0;g[9]=0;g[10]=-2/k;g[11]=0;g[12]=-(a+b)/h;g[13]=-(d+c)/j;g[14]=-(f+e)/k;g[15]=1;return g};
K.Ae=function(a,b,c,d){d||(d=K.create());var e,f,g,h,j,k,o,n,t=a[0],w=a[1],a=a[2];g=c[0];h=c[1];f=c[2];o=b[0];c=b[1];e=b[2];if(t===o&&w===c&&a===e)return K.Pa(d);b=t-o;c=w-c;o=a-e;n=1/Math.sqrt(b*b+c*c+o*o);b=b*n;c=c*n;o=o*n;e=h*o-f*c;f=f*b-g*o;g=g*c-h*b;if(n=Math.sqrt(e*e+f*f+g*g)){n=1/n;e=e*n;f=f*n;g=g*n}else g=f=e=0;h=c*g-o*f;j=o*e-b*g;k=b*f-c*e;if(n=Math.sqrt(h*h+j*j+k*k)){n=1/n;h=h*n;j=j*n;k=k*n}else k=j=h=0;d[0]=e;d[1]=h;d[2]=b;d[3]=0;d[4]=f;d[5]=j;d[6]=c;d[7]=0;d[8]=g;d[9]=k;d[10]=o;d[11]=
0;d[12]=-(e*t+f*w+g*a);d[13]=-(h*t+j*w+k*a);d[14]=-(b*t+c*w+o*a);d[15]=1;return d};K.Bg=function(a,b,c){c||(c=K.create());var d=a[0],e=a[1],f=a[2],g=a[3],h=d+d,j=e+e,k=f+f,a=d*h,o=d*j,d=d*k,n=e*j,e=e*k,f=f*k,h=g*h,j=g*j,g=g*k;c[0]=1-(n+f);c[1]=o+g;c[2]=d-j;c[3]=0;c[4]=o-g;c[5]=1-(a+f);c[6]=e+h;c[7]=0;c[8]=d+j;c[9]=e-h;c[10]=1-(a+n);c[11]=0;c[12]=b[0];c[13]=b[1];c[14]=b[2];c[15]=1;return c};
K.Qc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};Z.create=function(a){var b=new jb(4);if(a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3]}return b};Z.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b};
Z.yg=function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a===b){a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return a}b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b};Z.ga=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};Z.inverse=function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],c=(c=c*c+d*d+e*e+f*f)?1/c:0;if(!b||a===b){a[0]=a[0]*-c;a[1]=a[1]*-c;a[2]=a[2]*-c;a[3]=a[3]*c;return a}b[0]=-a[0]*c;b[1]=-a[1]*c;b[2]=-a[2]*c;b[3]=a[3]*c;return b};
Z.Wf=function(a,b){if(!b||a===b){a[0]=a[0]*-1;a[1]=a[1]*-1;a[2]=a[2]*-1}else{b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3]}};Z.length=function(a){var b=a[0],c=a[1],d=a[2],a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)};Z.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=Math.sqrt(c*c+d*d+e*e+f*f);if(g===0){b[0]=0;b[1]=0;b[2]=0;b[3]=0;return b}g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;b[3]=f*g;return b};
Z.add=function(a,b,c){if(!c||a===c){a[0]=a[0]+b[0];a[1]=a[1]+b[1];a[2]=a[2]+b[2];a[3]=a[3]+b[3];return a}c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];c[3]=a[3]+b[3];return c};Z.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],a=a[3],g=b[0],h=b[1],j=b[2],b=b[3];c[0]=d*b+a*g+e*j-f*h;c[1]=e*b+a*h+f*g-d*j;c[2]=f*b+a*j+d*h-e*g;c[3]=a*b-d*g-e*h-f*j;return c};
Z.wa=function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2],b=a[0],g=a[1],h=a[2],a=a[3],j=a*d+g*f-h*e,k=a*e+h*d-b*f,o=a*f+b*e-g*d,d=-b*d-g*e-h*f;c[0]=j*a+d*-b+k*-h-o*-g;c[1]=k*a+d*-g+o*-b-j*-h;c[2]=o*a+d*-h+j*-g-k*-b;return c};Z.scale=function(a,b,c){if(!c||a===c){a[0]=a[0]*b;a[1]=a[1]*b;a[2]=a[2]*b;a[3]=a[3]*b;return a}c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;c[3]=a[3]*b;return c};
Z.pg=function(a,b){b||(b=Y.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,h=d+d,j=e+e,k=c*g,o=c*h,c=c*j,n=d*h,d=d*j,e=e*j,g=f*g,h=f*h,f=f*j;b[0]=1-(n+e);b[1]=o+f;b[2]=c-h;b[3]=o-f;b[4]=1-(k+e);b[5]=d+g;b[6]=c+h;b[7]=d-g;b[8]=1-(k+n);return b};
Z.zd=function(a,b){b||(b=K.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,h=d+d,j=e+e,k=c*g,o=c*h,c=c*j,n=d*h,d=d*j,e=e*j,g=f*g,h=f*h,f=f*j;b[0]=1-(n+e);b[1]=o+f;b[2]=c-h;b[3]=0;b[4]=o-f;b[5]=1-(k+e);b[6]=d+g;b[7]=0;b[8]=c+h;b[9]=d-g;b[10]=1-(k+n);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};
Z.Ng=function(a,b,c,d){d||(d=a);var e=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3],f,g;if(Math.abs(e)>=1){if(d!==a){d[0]=a[0];d[1]=a[1];d[2]=a[2];d[3]=a[3]}return d}f=Math.acos(e);g=Math.sqrt(1-e*e);if(Math.abs(g)<0.001){d[0]=a[0]*0.5+b[0]*0.5;d[1]=a[1]*0.5+b[1]*0.5;d[2]=a[2]*0.5+b[2]*0.5;d[3]=a[3]*0.5+b[3]*0.5;return d}e=Math.sin((1-c)*f)/g;c=Math.sin(c*f)/g;d[0]=a[0]*e+b[0]*c;d[1]=a[1]*e+b[1]*c;d[2]=a[2]*e+b[2]*c;d[3]=a[3]*e+b[3]*c;return d};
Z.Qc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"};"undefined"!==typeof exports?global.D=global.D||{}:window.D=window.D||{};
function db(a){this.type=a;-1===this.type&&(a=[1,2,3,4,5,6,9,11],this.type=a[Math.floor(1E10*Math.random())%a.length]);this.Q=J.create([417,0.338,-395.164]);this.fa=J.create([0,0,0]);this.J=Z.create();Z.set([0,0.554,0,0.832],this.J);this.qa=J.create([0,0,0]);this.Hc=1200;this.qd=1/this.Hc;this.ec=1200;this.t=this.v=this.C=0;this.M=1;this.xe={10:-3.68,"0":0,1:4.06,2:2.4,3:1.58,4:1.19,5:1,6:0.87,9:3.8};this.ve=0.75;this.aa=new kb(this);this.Xb=J.create();this.Qb=J.create();this.Fb=K.create();this.bc=
K.create();this.mc=Z.create();this.nc=J.create();this.Ve=J.create();this.Ad=J.create();this.wg=J.create();this.mc=Z.create();this.wd=Z.create();this.ma=p;this.Dc=[];this.Ne=[];var b=0,c=0,d=a=0,c=2,e=0.5,b=0,f=1;switch(this.type){case 1:e=0.6;c=2.578;a=0.74;d=0.25;b=1;f=0;break;case 2:e=0.57;c=2.615;a=0.72;d=0.25;b=0.4;f=0.6;break;case 3:e=0.5;c=2.761;a=0.75;d=0.25;break;case 4:e=0.53;c=2.7;a=0.8;d=0.3;break;case 5:e=0.5;c=2.78;a=0.79;d=0.3;break;case 6:e=0.5;c=2.65;a=0.83;d=0.35;break;case 9:e=0.39;
c=2.35;a=0.75;d=0.3;break;case 11:e=0.5;c=2.56;a=0.82;d=0.35;b=0.4;f=0.6;break;default:e=0.5,c=2.761,a=0.79,d=0.25,b=0,f=1,console.log("default car values loaded!")}this.se=0.5*b;this.Ke=0.5*f;b=-c*(1-e);c*=e;this.j=[];this.j[0]=new lb([-a,d,b],1,this);this.j[1]=new lb([a,d,b],-1,this);this.j[2]=new lb([-a,d,c],1,this);this.j[3]=new lb([a,d,c],-1,this)}
db.prototype.getData=function(a,b){var c=new Uint8Array(a,b,4),d=new Float32Array(a,b+4);c[0]=this.type;c[1]=this.M;var c=0,e;d[c++]=this.Q[0];d[c++]=this.Q[1];d[c++]=this.Q[2];d[c++]=this.fa[0];d[c++]=this.fa[1];d[c++]=this.fa[2];d[c++]=this.J[0];d[c++]=this.J[1];d[c++]=this.J[2];d[c++]=this.J[3];d[c++]=this.qa[0];d[c++]=this.qa[1];d[c++]=this.qa[2];d[c++]=this.C;d[c++]=this.v;d[c++]=this.t;d[c++]=this.aa.L;for(e=0;4>e;e++)d[c++]=this.j[e].sb,d[c++]=this.j[e].Nb,d[c++]=this.j[e].hc,d[c++]=this.j[e].S};
db.prototype.toString=function(){var a=[],b=new ArrayBuffer(136);this.getData(b,0);for(var c=new Uint8Array(b),b=0;272>b;b++){var d=c[Math.ceil(b/2)],d=b&1?d&15:d>>>4;switch(d){case 0:a[b]="0";break;case 1:a[b]="1";break;case 2:a[b]="2";break;case 3:a[b]="3";break;case 4:a[b]="4";break;case 5:a[b]="5";break;case 6:a[b]="6";break;case 7:a[b]="7";break;case 8:a[b]="8";break;case 9:a[b]="9";break;case 10:a[b]="a";break;case 11:a[b]="b";break;case 12:a[b]="c";break;case 13:a[b]="d";break;case 14:a[b]=
"e";break;case 15:a[b]="f";break;default:a[b]="x"}}return a.join("")};
db.prototype.setData=function(a,b){var c=new Uint8Array(a,b,4),d=new Float32Array(a,b+4);this.M=c[1];var c=0,e;this.Q[0]=d[c++];this.Q[1]=d[c++];this.Q[2]=d[c++];this.fa[0]=d[c++];this.fa[1]=d[c++];this.fa[2]=d[c++];this.J[0]=d[c++];this.J[1]=d[c++];this.J[2]=d[c++];this.J[3]=d[c++];this.qa[0]=d[c++];this.qa[1]=d[c++];this.qa[2]=d[c++];this.C=d[c++];this.v=d[c++];this.t=d[c++];this.aa.L=d[c++];for(e=0;4>e;e++)this.j[e].sb=d[c++],this.j[e].Nb=d[c++],this.j[e].hc=d[c++],this.j[e].S=d[c++]};
function hb(a,b){switch(a.M){case 10:0.01>=a.v&&(0.01<=a.C&&0.02>J.length(a.fa))&&(a.M=0);0.01>=a.v&&a.aa.L<=a.aa.Ab&&(a.M=0);break;case 0:0.01>=a.C&&0.5<=a.v&&0.01>J.length(a.fa)?a.M=10:a.aa.L>a.aa.Ab+200&&a.M++;0.01>a.C&&0.5>a.v&&(a.v=0.49);break;case 1:case 2:case 3:case 4:case 5:a.aa.L>a.aa.Pf-100&&a.M++;a.aa.L<a.aa.Ab+200&&a.M--;break;case 6:a.aa.L<a.aa.Ab+10&&a.M--;break;default:console.warn("invalid gear: "+a.M)}a.j[0].Wc=a.t*a.ve*(0<a.t?1.2:0.9)/(Math.pow(J.length(a.fa)/8,2)+1);a.j[1].Wc=
a.t*a.ve*(0>a.t?1.2:0.9)/(Math.pow(J.length(a.fa)/8,2)+1);J.set([0,0,0],a.Xb);J.set([0,0,0],a.Qb);var c=a.Ad;Z.wa(a.J,a.fa,a.Ve);var d=a.xe[a.M]*a.xe[9],e=50*(a.aa.L-0.25*(a.j[0].S+a.j[1].S+a.j[2].S+a.j[3].S)*d),e=Math.min(e,2E3);0===a.M&&(e=0);a.aa.step(10===a.M?a.v:a.C,e,b);d=e*d/1;mb(a.j[0],d*a.se,b);mb(a.j[1],d*a.se,b);mb(a.j[2],d*a.Ke,b);mb(a.j[3],d*a.Ke,b);s.Da.Cb(a.Qb,a.qa,-0.001);s.Da.Cb(a.Xb,a.Ve,-0.001);Z.wa(a.J,a.Xb);nb(a,[0,0,0],[0,9.8*-a.Hc,0]);d=J.length(a.qa);0<d&&(J.scale(a.qa,1/d,
c),s.ud(d*b,c,m,a.mc),Z.multiply(a.J,a.mc),Z.normalize(a.J),Z.Wf(a.J,a.wd));J.add(a.qa,J.scale(a.Qb,b/a.ec));J.add(a.Q,J.scale(a.fa,b,c));J.add(a.fa,J.scale(a.Xb,b*a.qd,c));K.Pa(a.Fb);K.translate(a.Fb,a.Q);K.multiply(a.Fb,Z.zd(a.J));a.bc=K.inverse(a.Fb,a.bc)}function nb(a,b,c){J.add(a.Xb,c);J.add(a.Qb,J.kb(b,c,a.Ad))}function kb(a){this.l=a;this.bg=0.1;this.cg=20;this.ec=0.2;this.rd=1/this.ec;this.Ab=105;this.Pf=830;this.L=this.Ab;this.pe=[0,280,300,340,390,400,400,360,340,0]}
kb.prototype.step=function(a,b,c){var a=this.Qb()*a,d=Math.min(this.L*this.bg,this.cg);this.L+=(a-d-b)*this.rd*c;this.L=Math.max(this.L,this.Ab)};kb.prototype.Qb=function(){var a=0.00955*this.L,b=Math.floor(a),c=Math.ceil(a);b===c&&c++;a-=b;b=s.sa(b,0,9);c=s.sa(c,0,9);return 2*(this.pe[b]*a+this.pe[c]*(1-a))};
function lb(a,b,c){this.o=J.create(a);this.Lb=0.3305;this.Wc=0;this.rotate=b;this.l=c;this.je=J.create();this.re=J.create();this.Hc=10;this.qd=1/this.Hc;this.ec=10;this.rd=1/this.ec;this.Be=0.18;this.kc=J.create([0,1,0]);this.sb=-0.1;this.yd=-0.2;this.Nb=0;this.mg=75E3;this.lg=8E3;this.Sb=J.create();this.Xc=J.create();this.Dd=J.create();this.Xf=J.create();this.oe=J.create();this.qg=J.create();this.rg=J.create();this.sg=J.create();this.tg=J.create();this.ug=J.create();this.vg=J.create();this.hc=0;
this.S=0.01}
function mb(a,b,c){var d=a.l.Ad,e=a.l.wg,f,g=a.qg,h=a.Xf,j=a.oe,k,o,n,t=a.rg,w=a.sg,v=a.tg,C=a.Dd,F=a.ug;k=a.vg;o=0;J.set([0,0,0],a.Sb);J.set([0,0,0],v);f=a.mg*(a.sb-a.yd)+a.lg*a.Nb;4E4<Math.abs(f)&&(f=4E4*s.rb(f));K.wa(a.l.Fb,a.je,F);Z.wa(a.l.J,a.kc,k);J.scale(k,-1);n=a.l.ma;o=q;o=n.ic(F,k,2);o!==q&&(k=n.Jb,o=n.ta-a.Lb,n=n.Ob,1.0E-5>o&&(Z.wa(a.l.wd,k,t),J.add(F,J.scale(k,-a.Lb,d),j),K.wa(a.l.bc,j,h),Z.wa(a.l.wd,a.l.fa,g),J.add(g,J.kb(a.l.qa,h,d)),J.za(g,J.scale(t,J.ga(t,g),d)),j=Math.min(2E6*-o,
8E4),J.scale(t,j,a.Sb),s.ud(a.Wc,t,q,a.l.mc),Z.wa(a.l.mc,[0,0,-1],w),F=a.S*a.Lb-J.ga(g,w),k=J.length(g)||1.0E-4,1>k&&(k=Math.pow(k,0.001)),F=s.sa(F/k,-1*a.Be,a.Be),J.scale(w,F*(n?4:8)*j,a.Xc),J.kb(w,t,C),F=J.ga(g,C),g=J.ga(g,w)-a.S*a.Lb,1>Math.abs(g)&&(g=Math.pow(Math.abs(g),0.001)*(0<g?-1:1)),o=Math.atan(F/g)*(0<g?-1:1),o*=180/Math.PI,o=s.sa(o,-3.273,3.273),J.scale(C,o*(n?0.4891:0.8891)*j),J.add(v,a.Xc),J.add(v,C),J.add(v,a.Sb),J.za(v,J.scale(t,J.ga(t,v),d),e),nb(a.l,h,e)));J.scale(a.kc,f,d);nb(a.l,
a.o,d);e=J.ga(v,w);50>Math.abs(e)&&(e=0);h=10===a.l.M?a.l.C:a.l.v;t=Math.min(500*a.S*h-e*h,5E3);w=2*a.S;a.sb+=a.Nb*c;a.Nb+=(J.ga(a.kc,a.Sb)-f)*a.qd*c;a.hc+=a.S*c;a.S+=(b-w-t-e)*a.rd*c;0.1>Math.abs(a.S)&&0.5<h&&(a.S=0);J.add(a.o,J.scale(a.kc,a.sb,d),a.je);b=a.sb;0.15<b-a.yd&&(b=a.yd+0.15);J.add(a.o,J.scale(a.kc,b,d),a.re)}
function eb(a,b,c){this.l=a;this.ca=b;this.d=b.d;this.$b=c===m?m:q;this.ag=J.create();var d,e,f="admin_add.png",g,h,c=B(b,"car");this.h=p;switch(this.l.type){case 1:d="b3.obj";e="b3.png";f="b3_add.png";h=[0.7,0,0];g=J.create([0,0.36,1.54]);break;case 2:d="alpha.obj";e="alpha.png";f="alpha_add.png";h=[0,0,0.1];g=J.create([0,0.09,1.49]);break;case 3:d="ulf.obj";e="ulf.png";f="ulf_add.png";h=[0,0,0.1];g=J.create([0,0.02,1.38]);break;case 4:d="head.obj";e="head.png";f="head_add.png";h=[0.05,0,0];g=J.create([0,
0.07,1.43]);break;case 5:d="f35.obj";e="f35.png";f="f35_add.png";h=[0.129,0,0.26];g=J.create([0,0.07,1.39]);break;case 6:d="arosa.obj";e="arosa.png";f="arosa_add.png";h=[0.9,0.9,0.9];g=J.create([0,0.12,1.325]);break;case 9:d="r500.obj";e="r500.png";f="r500_add.png";h=[0.43,0.19,0.04];g=J.create([0,0.12,0.91]);break;case 11:d="admin.obj";e="admin.png";f="admin_add.png";h=[0.4,0.9,0];g=J.create([0,0.16,1.28]);break;default:d="ulf.obj",e="ulf.png",f="ulf_add.png",h=[0.43,0.19,0.04],g=J.create([0,0.27,
0.11]),console.log("wrong car type: "+a.type)}this.body=new L(I(b,d),c,G(b,e,q));this.body.ub=G(b,f,q);this.body.vb=G(b,"dangus.jpg");this.body.e[s.b.p]=h;this.body.o=g;e=G(b,"ratai.png",m,m);d=I(b,"ratai.obj");this.j=[];for(a=0;4>a;a++)this.j[a]=new L(d,c,e),this.j[a].ub=G(b,"ratai_add.png",q),this.j[a].vb=G(b,"dangus.jpg"),this.j[a].e[s.b.p]=[0.5,0.5,0.5];this.k=[];this.$b&&gb(this)}
function gb(a){var b=B(a.ca,"color");a.k[0]=new L(new $(a.d),b);a.k[0].e[s.b.p]=[0,1,0];a.k[1]=new L(new $(a.d),b);a.k[1].e[s.b.p]=[1,1,0];a.k[2]=new L(new $(a.d),b);a.k[2].e[s.b.p]=[0,1,0];a.k[3]=new L(new $(a.d),b);a.k[3].e[s.b.p]=[0,1,1];a.k[4]=new L(new $(a.d),b);a.k[4].e[s.b.p]=[1,1,0];a.k[5]=new L(new $(a.d),b);a.k[5].e[s.b.p]=[1,0,0];a.k[6]=new L(new $(a.d),b);a.k[6].e[s.b.p]=[0,1,1];a.k[7]=new L(new $(a.d),b);a.k[7].e[s.b.p]=[0,1,0];a.k[8]=new L(new $(a.d),b);a.k[8].e[s.b.p]=[1,0,0];a.k[9]=
new L(new $(a.d),b);a.k[9].e[s.b.p]=[1,0,1];a.k[10]=new L(new $(a.d),b);a.k[10].e[s.b.p]=[0,0,1];a.k[11]=new L(new $(a.d),b);a.k[11].e[s.b.p]=[1,0,0];if(a.h)for(b=a.k.length-1;0<=b;b--)a.h.add(a.k[b],m)}
function ib(a){var b=a.l.Fb,c=a.body.w,d=a.ag;K.set(b,c);K.translate(c,a.body.o);K.Pb(a.body.w,a.body.ba);Y.xb(a.body.ba);for(c=0;4>c;c++){var e=a.j[c],f=e.w,g=a.l.j[c],h=g.oe;K.set(b,f);K.translate(f,g.re);K.rotate(f,g.Wc,[0,1,0]);K.rotate(f,g.hc,[-1,0,0]);K.rotate(f,0.5*Math.PI*g.rotate,[0,0,1]);K.Pb(e.w,e.ba);Y.xb(e.ba);a.$b&&(Z.wa(a.l.J,g.Sb,d),J.scale(d,1/3E3),J.set(h,a.k[c].m.Kc),J.set(d,a.k[c].m.Mc),a.k[c].m.apply(),Z.wa(a.l.J,g.Xc,d),J.scale(d,1/3E3),J.set(h,a.k[c+4].m.Kc),J.set(d,a.k[c+4].m.Mc),
a.k[c+4].m.apply(),Z.wa(a.l.J,g.Dd,d),J.scale(d,1/3E3),J.set(h,a.k[c+8].m.Kc),J.set(d,a.k[c+8].m.Mc),a.k[c+8].m.apply())}}eb.prototype.ie=function(a){this.h=a;a.add(this.body);a.add(this.j[0]);a.add(this.j[1]);a.add(this.j[2]);a.add(this.j[3]);var b,c;for(b=0;c=this.k[b];b++)a.add(c,m)};
function fb(a,b){a.h=p;b.da.splice(b.da.indexOf(a.body),1);b.da.splice(b.da.indexOf(a.j[0]),1);b.da.splice(b.da.indexOf(a.j[1]),1);b.da.splice(b.da.indexOf(a.j[2]),1);b.da.splice(b.da.indexOf(a.j[3]),1);var c;if(a.$b)for(c=a.k.length-1;0<=c;c--)b.lb.splice(b.lb.indexOf(a.k[c]),1)}
function $a(a,b,c){this.l=a;this.g=b;this.g.Y&&(this.destination=c||b.Zb,this.Ta=b.Y.createPanner(),this.Ta.connect(this.destination),this.A=[],this.A[0]=la(b,"offlow.ogg",this.Ta),this.A[1]=la(b,"offmid.ogg",this.Ta),this.A[2]=la(b,"offhigh.ogg",this.Ta),this.A[3]=la(b,"onlow.ogg",this.Ta),this.A[4]=la(b,"onmid.ogg",this.Ta),this.A[5]=la(b,"onhigh.ogg",this.Ta),this.A[0].Va=2,this.A[1].Va=2,this.A[2].Va=2,this.A[3].Va=2,this.A[4].Va=2,this.A[5].Va=2,this.A[0].noteOn(0),this.A[1].noteOn(0),this.A[2].noteOn(0),
this.A[3].noteOn(0),this.A[4].noteOn(0),this.A[5].noteOn(0))}$a.prototype.remove=function(){this.g.Y&&(this.A[0].noteOff(0),this.A[1].noteOff(0),this.A[2].noteOff(0),this.A[3].noteOff(0),this.A[4].noteOff(0),this.A[5].noteOff(0),this.A=[])};
$a.prototype.update=function(a){if(this.g.Y){var b=10*this.l.aa.L,c=this.l.C,d=this.A,e=[3150,3990,6450];d[0]&&(d[0].playbackRate.value=b/e[0],d[0].gain.value=b<e[0]?1*(1-c):1*(1-c)*Math.max((e[1]-b)/(e[1]-e[0]),0));d[1]&&(d[1].playbackRate.value=b/e[1],d[1].gain.value=b<e[1]?1*(1-c)*Math.max((b-e[0])/(e[1]-e[0]),0):1*(1-c)*Math.max((e[2]-b)/(e[2]-e[1]),0));d[2]&&(d[2].playbackRate.value=b/e[2],d[2].gain.value=b<e[2]?1*(1-c)*Math.max((b-e[1])/(e[2]-e[1]),0):1*(1-c));d[3]&&(d[3].playbackRate.value=
b/e[0],d[3].gain.value=b<e[0]?1*c:1*c*Math.max((e[1]-b)/(e[1]-e[0]),0));d[4]&&(d[4].playbackRate.value=b/e[1],d[4].gain.value=b<e[1]?1*c*Math.max((b-e[0])/(e[1]-e[0]),0):1*c*Math.max((e[2]-b)/(e[2]-e[1]),0));d[5]&&(d[5].playbackRate.value=b/e[2],d[5].gain.value=b<e[2]?1*c*Math.max((b-e[1])/(e[2]-e[1]),0):1*c);for(b=0;b<d.length;b++)if(0>=d[b].gain.value&&2===d[b].Va&&(d[b].noteOff(0),c=d[b].buffer,e=d[b].gain.value,d[b]=this.g.Y.createBufferSource(),d[b].buffer=c,d[b].loop=m,d[b].connect(this.Ta),
d[b].gain.value=e,d[b].Va=0),0<d[b].gain.value&&0===d[b].Va)d[b].noteOn(0),d[b].Va=2;d=J.create();b=J.create();J.za(this.l.Q,a.position,b);c=Math.sin(a.rotation[1]);a=Math.cos(a.rotation[1]);d[0]=b[0]*a-b[2]*c;d[1]=b[1];d[2]=b[0]*c+b[2]*a;this.Ta.setPosition(0.2*d[0],0.2*d[1],0.2*d[2])}};"undefined"!==typeof exports?global.D=global.D||{}:window.D=window.D||{};s.od=function(a,b,c,d){return a*c+b*d};s.rb=function(a){return 0>a?-1:1};s.sa=function(a,b,c){return Math.min(c,Math.max(b,a))};s.ud=function(a,b,c,d){c!==m&&J.normalize(b);a*=0.5;c=Math.sin(a);Z.set([b[0]*c,b[1]*c,b[2]*c,Math.cos(a)],d)};s.gc=function(a,b){var c=s.sa(b-a.length,0,256);return Array(c+1).join(" "[0])+a};s.Da={};
s.Da.Qc=function(a,b){b===l&&(b=3);return"["+a[0].toFixed(b)+", "+a[1].toFixed(b)+", "+a[2].toFixed(b)+"]"};s.Da.kg=function(a,b){return(a[0]-b[0])*(a[0]-b[0])+(a[1]-b[1])*(a[1]-b[1])+(a[2]-b[2])*(a[2]-b[2])};s.Da.Cb=function(a,b,c){a[0]+=b[0]*c;a[1]+=b[1]*c;a[2]+=b[2]*c};s.sd=function(a,b){if("undefined"===typeof exports){var c;c=new XMLHttpRequest;c.open("GET",a);c.onreadystatechange=function(){4===c.readyState&&b(c.responseText)};c.send()}else fs.readFile(a,"utf-8",function(a,c){b(c)})};
s.fg=function(){return"undefined"!==typeof exports};"undefined"!==typeof exports?global.D=global.D||{}:window.D=window.D||{};function L(a,b,c){this.m=a;this.na=b;this.e=[];this.Na=m;this.Ja=q;this.tb=c!==l?c:p;this.Rc=this.vb=this.ub=p;this.o=J.create();this.J=Z.create([0,0,0,1]);this.w=K.create();this.ba=Y.create();this.$=this.ua=m;this.K=0;this.mb=m}L.prototype.dd=function(){K.Pa(this.w);K.translate(this.w,this.o);K.multiply(this.w,Z.zd(this.J));K.Pb(this.w,this.ba);Y.xb(this.ba);this.$=q};function Ma(a){a.$&&a.dd();return a.w}
function ob(){this.W=q;this.q={};this.e=[]}ob.prototype.Ac=aa();function $(a,b){ob.call(this);this.d=a;this.Kc=J.create([5,0,0]);this.Mc=J.create([0,10,0]);this.add=b===l?m:b;this.xg=new Float32Array(6);this.apply();this.W=m}
$.prototype.apply=function(){var a=this.Kc,b=this.Mc,c=this.xg;c[0]=a[0];c[1]=a[1];c[2]=a[2];this.add?(c[3]=a[0]+b[0],c[4]=a[1]+b[1],c[5]=a[2]+b[2]):(c[3]=b[0],c[4]=b[1],c[5]=b[2]);a=this.d;this.q.ra=this.q.ra||a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,this.q.ra);a.bufferData(a.ARRAY_BUFFER,c,a.STREAM_DRAW)};$.prototype.Ac=function(a,b){Va(b,"aVerPosition");Wa(b,"aVerPosition",this.q.ra,3);a.disable(a.DEPTH_TEST);a.drawArrays(a.LINES,0,2);a.enable(a.DEPTH_TEST)};
$.prototype.Bb=function(a,b){Va(b,"aVerPosition");Wa(b,"aVerPosition",this.q.ra,3);a.disable(a.DEPTH_TEST);a.drawArrays(a.LINES,0,2);a.enable(a.DEPTH_TEST)};
function Ta(a,b,c,d){ob.call(this);var e=this;this.d=a;this.X=b;s.fg()||(this.e[s.b.Rb]=[0],this.e[s.b.Uc]=[1],this.e[s.b.Se]=[2],this.e[s.b.Te]=[3]);this.root=c;this.Ha=this.B=this.ha=p;this.Eb=d===l?p:d;this.V=0;this.te=this.lc=this.fc=q;this.eb=this.N=this.O=p;this.ng=J.create();this.Zf=J.create();this.Yf=J.create();this.Sf=J.create();this.Tf=J.create();this.Uf=J.create();this.og=J.create();this.Yb=J.create();this.Jb=J.create();this.ta=0;s.sd(this.X,function(a){e.jd(a)})}
Ta.prototype.jd=function(a){var b,c,d,e,f,g,h,j;j=[];var k=[],o=[],n=[];f=J.create();g=J.create();J.create();h=J.create();a=a.split("\n");for(c=0;c<a.length;c++)if(0!==a[c].length&&(b=a[c].split(" "),0!==b.length))switch(b[0]){case "v":4===b.length?(d=[parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3])],!isNaN(d[0])&&!isNaN(d[1])&&!isNaN(d[2])?j.push(d):console.error("Bad vertex data in "+this.X+":"+c)):console.error("Wrong vertex data count in "+this.X+":"+c);break;case "f":this.te||(this.fc=0<n.length,
this.lc=0<o.length,this.te=m);4===b.length?(d=b[1].split("/"),e=b[2].split("/"),b=b[3].split("/"),d=[parseInt(d[0],10),parseInt(e[0],10),parseInt(b[0],10),parseInt(d[1],10),parseInt(e[1],10),parseInt(b[1],10),parseInt(d[2],10),parseInt(e[2],10),parseInt(b[2],10)],!isNaN(d[0])&&!isNaN(d[1])&&!isNaN(d[2])?k.push(d):console.error("Bad vertex data in "+this.X+":"+c)):console.error("Wrong face data count in "+this.X+":"+c);break;case "vt":3===b.length?(d=[parseFloat(b[1]),parseFloat(b[2])],!isNaN(d[0])&&
!isNaN(d[1])?o.push(d):console.error("Bad vertex texture data in "+this.X+":"+c)):console.error("Bad vertex texture data in "+this.X+":"+c);break;case "vn":4===b.length?(d=[parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3])],!isNaN(d[0])&&!isNaN(d[1])&&!isNaN(d[2])?n.push(d):console.error("Bad vertex normal data in "+this.X+":"+c)):console.error("Bad vertex normal data in "+this.X+":"+c)}this.V=k.length;this.O=new Float32Array(9*this.V);this.fc===m&&(this.N=new Float32Array(9*this.V));this.lc===m&&
(this.eb=new Float32Array(6*this.V));if(this.root===m){this.ha=new Int16Array(3*this.V);this.B=new Float32Array(3*j.length);this.Ha=new Float32Array(3*this.V);for(a=0;a<this.V;a++)this.ha[3*a]=k[a][0]-1,this.ha[3*a+1]=k[a][1]-1,this.ha[3*a+2]=k[a][2]-1;for(a=j.length-1;-1!==a;a-=1)this.B[3*a]=j[a][0],this.B[3*a+1]=j[a][1],this.B[3*a+2]=j[a][2];for(a=0;a<this.V;a++)d=j[k[a][0]-1],e=j[k[a][1]-1],b=j[k[a][2]-1],J.za(d,e,f),J.za(e,b,g),J.kb(f,g,h),J.normalize(h),this.Ha[3*a+0]=h[0],this.Ha[3*a+1]=h[1],
this.Ha[3*a+2]=h[2]}for(a=0;a<this.V;a++)if(d=j[k[a][0]-1],e=j[k[a][1]-1],b=j[k[a][2]-1],this.O[9*a]=d[0],this.O[9*a+1]=d[1],this.O[9*a+2]=d[2],this.O[9*a+3]=e[0],this.O[9*a+4]=e[1],this.O[9*a+5]=e[2],this.O[9*a+6]=b[0],this.O[9*a+7]=b[1],this.O[9*a+8]=b[2],this.fc&&(f=n[k[a][6]-1],g=n[k[a][7]-1],h=n[k[a][8]-1],this.N[9*a]=f[0],this.N[9*a+1]=f[1],this.N[9*a+2]=f[2],this.N[9*a+3]=g[0],this.N[9*a+4]=g[1],this.N[9*a+5]=g[2],this.N[9*a+6]=h[0],this.N[9*a+7]=h[1],this.N[9*a+8]=h[2]),this.lc)f=o[k[a][3]-
1],g=o[k[a][4]-1],h=o[k[a][5]-1],this.eb[6*a]=f[0],this.eb[6*a+1]=f[1],this.eb[6*a+2]=g[0],this.eb[6*a+3]=g[1],this.eb[6*a+4]=h[0],this.eb[6*a+5]=h[1];if("undefined"===typeof exports&&(j=this.d,this.q.ra=j.createBuffer(),j.bindBuffer(j.ARRAY_BUFFER,this.q.ra),j.bufferData(j.ARRAY_BUFFER,this.O,j.STATIC_DRAW),this.fc&&(this.q.Vb=j.createBuffer(),j.bindBuffer(j.ARRAY_BUFFER,this.q.Vb),j.bufferData(j.ARRAY_BUFFER,this.N,j.STATIC_DRAW)),this.lc))this.q.ke=j.createBuffer(),j.bindBuffer(j.ARRAY_BUFFER,
this.q.ke),j.bufferData(j.ARRAY_BUFFER,this.eb,j.STATIC_DRAW);var t=this;this.root?setTimeout(function(){var a;t.root=new pb(t);for(a=0;a<t.V;a++)t.root.add(a);qb(t.root,0);if(t.Eb){t.Eb();t.Eb=p}},1):this.Eb&&(this.Eb(),this.Eb=p);this.W=m};
Ta.prototype.Ac=function(a,b,c){Wa(b,"aVerPosition",this.q.ra,3);if(b.attributes.aVerNormal!==l)if(this.fc===m)Va(b,"aVerNormal"),Wa(b,"aVerNormal",this.q.Vb,3);else{var d=b.attributes.aVerNormal;d===l?console.warn("Bad shader attribute name!"):b.Ub[d]===m&&(b.Ia.disableVertexAttribArray(d),b.Ub[d]=q)}this.lc&&c.tb&&(Va(b,"aTexCoord"),Wa(b,"aTexCoord",this.q.ke,2),b.bindTexture(0,c.tb.ia),c.ub&&b.bindTexture(1,c.ub.ia),c.vb&&b.bindTexture(2,c.vb.ia),c.Rc&&b.bindTexture(3,c.Rc.ia));a.drawArrays(a.TRIANGLES,
0,3*this.V)};Ta.prototype.Bb=function(a,b){Wa(b,"aVerPosition",this.q.ra,3);a.drawArrays(a.TRIANGLES,0,3*this.V)};function ab(a,b,c){ob.call(this);var d=this;this.d=a;this.X=b;this.bd=c===l?p:c;this.ob={"":0};this.size={};s.sd(this.X,function(a){d.jd(a)})}
ab.prototype.jd=function(a){var b,c,d,e,f;f="";var g;g=[];var h=[],j=[],a=a.split("\n");for(c=0;c<a.length;c++)if(0!==a[c].length&&(b=a[c].split(" "),0!==b.length))switch(b[0]){case "g":this.ob[b[1][0]]=h.length;this.size[f]=h.length-this.ob[f];f=b[1][0];break;case "v":4===b.length?(d=[parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3])],!isNaN(d[0])&&!isNaN(d[1])&&!isNaN(d[2])?g.push(d):console.error("Bad vertex data in "+this.X+":"+c)):console.error("Wrong vertex data count in "+this.X+":"+c);break;
case "vn":4===b.length?(d=[parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3])],!isNaN(d[0])&&!isNaN(d[1])&&!isNaN(d[2])?j.push(d):console.error("Bad vertex normal data in "+this.X+":"+c)):console.error("Bad vertex normal data in "+this.X+":"+c);break;case "f":4===b.length?(d=b[1].split("/"),e=b[2].split("/"),b=b[3].split("/"),d=[parseInt(d[0],10),parseInt(e[0],10),parseInt(b[0],10),parseInt(d[1],10),parseInt(e[1],10),parseInt(b[1],10),parseInt(d[2],10),parseInt(e[2],10),parseInt(b[2],10)],!isNaN(d[0])&&
!isNaN(d[1])&&!isNaN(d[2])?h.push(d):console.error("Bad vertex data in "+this.X+":"+c)):console.error("Wrong face data count in "+this.X+":"+c)}this.size[f]=h.length-this.ob[f];this.V=h.length;this.O=new Float32Array(9*this.V);this.N=new Float32Array(9*this.V);for(f=0;f<this.V;f++)d=g[h[f][0]-1],e=g[h[f][1]-1],b=g[h[f][2]-1],this.O[9*f]=d[0],this.O[9*f+1]=d[1],this.O[9*f+2]=d[2],this.O[9*f+3]=e[0],this.O[9*f+4]=e[1],this.O[9*f+5]=e[2],this.O[9*f+6]=b[0],this.O[9*f+7]=b[1],this.O[9*f+8]=b[2],a=j[h[f][6]-
1],c=j[h[f][7]-1],d=j[h[f][8]-1],this.N[9*f]=-a[0],this.N[9*f+1]=-a[1],this.N[9*f+2]=-a[2],this.N[9*f+3]=-c[0],this.N[9*f+4]=-c[1],this.N[9*f+5]=-c[2],this.N[9*f+6]=-d[0],this.N[9*f+7]=-d[1],this.N[9*f+8]=-d[2];g=this.d;this.q.ra=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.q.ra);g.bufferData(g.ARRAY_BUFFER,this.O,g.STATIC_DRAW);this.q.Vb=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.q.Vb);g.bufferData(g.ARRAY_BUFFER,this.N,g.STATIC_DRAW);this.W=m;"function"==typeof this.bd&&(this.bd(),this.bd=
p)};ab.prototype.Ac=function(a,b,c){"string"!==typeof c.text&&i(Error("TextMesh objects must have a text string!"));var d=b.ja[b.pa.indexOf(s.b.pc)];Va(b,"aVerPosition");Wa(b,"aVerPosition",this.q.ra,3);Va(b,"aVerNormal");Wa(b,"aVerNormal",this.q.Vb,3);for(b=0;b<c.text.length;b++){var e=c.text[b].toLowerCase();" "!==e&&(this.ob[e]===l&&(e="_"),a.uniform1i(d,b),a.drawArrays(a.TRIANGLES,3*this.ob[e],3*this.size[e]))}};
ab.prototype.Bb=function(a,b,c){"string"!==typeof c.text&&i(Error("TextMesh objects must have a text string!"));var d=b.ja[b.pa.indexOf(s.b.pc)];Va(b,"aVerPosition");Wa(b,"aVerPosition",this.q.ra,3);for(b=0;b<c.text.length;b++){var e=c.text[b].toLowerCase();" "!==e&&(this.ob[e]===l&&(e="_"),a.uniform1i(d,b),a.drawArrays(a.TRIANGLES,3*this.ob[e],3*this.size[e]))}};"undefined"!==typeof exports?global.D=global.D||{}:window.D=window.D||{};function pb(a){this.m=a;this.min=J.create();this.max=J.create();this.oa=[];this.Sa=this.Xa=p;this.Yb=J.create();this.Jb=J.create();this.ta=0}pb.prototype.add=function(a){this.oa.push(a)};
function qb(a,b){var c,d,e,f,g,h,j,k;a.min[0]=1E10;a.min[1]=1E10;a.min[2]=1E10;a.max[0]=-1E10;a.max[1]=-1E10;a.max[2]=-1E10;for(c=0;c<a.oa.length;c++){d=3*a.oa[c];for(e=0;3>e;e++)for(g=0;3>g;g++)f=a.m.B[3*a.m.ha[d+e]+g],f>a.max[g]&&(a.max[g]=f),f<a.min[g]&&(a.min[g]=f)}0===a.oa.length&&console.log(0);if(2<a.oa.length&&50>b){c=a.max[0]-a.min[0]>a.max[2]-a.min[2]?0:2;d=(a.split=c)?(a.max[2]+a.min[2])/2:(a.max[0]+a.min[0])/2;k=c?(a.max[2]-a.min[2])/4:(a.max[0]-a.min[0])/4;a.Xa=new pb(a.m);a.Sa=new pb(a.m);
for(j=[];(e=a.oa.pop())!==l;)g=h=a.m.B[3*a.m.ha[3*e]+c],f=a.m.B[3*a.m.ha[3*e+1]+c],f<g&&(g=f),f>h&&(h=f),f=a.m.B[3*a.m.ha[3*e+2]+c],f<g&&(g=f),f>h&&(h=f),d-g>k&&h-d>k?j.push(e):d-g>h-d?a.Sa.add(e):a.Xa.add(e);a.oa=j;0===a.Xa.oa.length?a.Xa=p:qb(a.Xa,b+1);0===a.Sa.oa.length?a.Sa=p:qb(a.Sa,b+1)}}
pb.prototype.rc=function(a,b){if(a<this.min[0]||a>this.max[0]||b>this.max[2]||b<this.min[2])return q;var c,d=-100,e=[0,1,0],f;for(f=this.oa.length-1;0<=f;f--){var g=this.oa[f],h=c=l,j=l,k=j=l,k=j=h=l,g=g+g+g,k=this.m,j=3*k.ha[g];c=[k.B[j++],k.B[j++],k.B[j]];j=3*k.ha[g+1];h=[k.B[j++],k.B[j++],k.B[j]];0<s.od(a-c[0],b-c[2],c[2]-h[2],h[0]-c[0])?c=q:(j=3*k.ha[g+2],j=[k.B[j++],k.B[j++],k.B[j]],0<s.od(a-h[0],b-h[2],h[2]-j[2],j[0]-h[0])||0<s.od(a-j[0],b-j[2],j[2]-c[2],c[0]-j[0])?c=q:(h=k.Ha[g++],j=k.Ha[g++],
k=k.Ha[g],c=0===h&&0===j&&0===k?q:{r:(h*a+k*b-(h*c[0]+j*c[1]+k*c[2]))/-j,n:[h,j,k]}));c!==q&&c.cb>d&&(d=c.cb,e=c.td)}this.Xa!==p&&(c=this.Xa.rc(a,b),c!==q&&c.cb>d&&(d=c.cb,e=c.td));this.Sa!==p&&(c=this.Sa.rc(a,b),c!==q&&c.cb>d&&(d=c.cb,e=c.td));return{r:d,n:e}};
pb.prototype.ic=function(a,b,c){c!==l?this.m.ta=c:c=this.m.ta;var d,e=100000.1,f=-100000.1,g,h;for(d=2;0<=d;d--)if(0===b[d]){if(a[d]<this.min[d]||a[d]>this.max[d])return q}else if(g=(this.min[d]-a[d])/b[d],h=(this.max[d]-a[d])/b[d],g>h?(h>f&&(f=h),g<e&&(e=g)):(g>f&&(f=g),h<e&&(e=h)),f>e||0>=e||f>c)return q;for(d=this.oa.length-1;0<=d;d--){e=a;f=b;g=this.oa[d];var j=g+g+g,k=l;g=l;g=this.m;h=g.ng;var o=g.Zf,n=g.Yf,t=g.og,w=g.Sf,v=g.Tf,C=g.Uf,k=3*g.ha[j];w[0]=g.B[k++];w[1]=g.B[k++];w[2]=g.B[k];k=3*g.ha[j+
1];v[0]=g.B[k++];v[1]=g.B[k++];v[2]=g.B[k];k=3*g.ha[j+2];C[0]=g.B[k++];C[1]=g.B[k++];C[2]=g.B[k];t[0]=g.Ha[j++];t[1]=g.Ha[j++];t[2]=g.Ha[j];j=J.ga(t,f);0!==j&&(j=-1*(J.ga(e,t)+-1*J.ga(t,w))/j,j>=g.ta||0>j||(J.scale(f,j,h),J.add(h,e),J.za(w,v,n),J.kb(n,t),J.za(h,w,o),0>J.ga(n,o)||(J.za(v,C,n),J.kb(n,t),J.za(h,v,o),0>J.ga(n,o)||(J.za(C,w,n),J.kb(n,t),J.za(h,C,o),0>J.ga(n,o)||(J.set(h,g.Yb),J.set(t,g.Jb),g.ta=j)))))}this.Xa!==p&&this.Xa.ic(a,b);this.Sa!==p&&this.Sa.ic(a,b);return this.m.ta===c?q:m};
function Za(){this.bb=[];this.root={};this.Yb=J.create();this.Jb=J.create();this.Ob=this.ta=0}Za.prototype.ic=function(a,b,c){var d,e=q;this.ta=c;for(c=this.bb.length-1;0<=c;c--)d=this.bb[c],d.root.ic(a,b,this.ta)===m&&(J.set(d.Yb,this.Yb),J.set(d.Jb,this.Jb),this.ta=d.ta,this.Ob=d.Ob,e=m);return e};Za.prototype.rc=function(a,b){var c,d,e=-100,f=[0,1,0];for(c=this.bb.length-1;0<=c;c--)d=this.bb[c],d=d.root.rc(a,b),d!==q&&d.cb>e&&(e=d.cb,f=d.td);return{r:e,n:f}};
